// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: glyph/proto/canvas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompositionEdge represents a directed edge in the composition DAG
// Supports multi-directional melding: horizontal (right), vertical (top/bottom)
type CompositionEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`           // source glyph ID
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`               // target glyph ID
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"` // 'right', 'top', 'bottom'
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`  // ordering for multiple edges in same direction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositionEdge) Reset() {
	*x = CompositionEdge{}
	mi := &file_glyph_proto_canvas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositionEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositionEdge) ProtoMessage() {}

func (x *CompositionEdge) ProtoReflect() protoreflect.Message {
	mi := &file_glyph_proto_canvas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositionEdge.ProtoReflect.Descriptor instead.
func (*CompositionEdge) Descriptor() ([]byte, []int) {
	return file_glyph_proto_canvas_proto_rawDescGZIP(), []int{0}
}

func (x *CompositionEdge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CompositionEdge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CompositionEdge) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CompositionEdge) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

// Composition represents a DAG of melded glyphs
// Edges define the graph structure - no derived fields
type Composition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Edges         []*CompositionEdge     `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	X             float64                `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"` // anchor X position in pixels
	Y             float64                `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"` // anchor Y position in pixels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Composition) Reset() {
	*x = Composition{}
	mi := &file_glyph_proto_canvas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Composition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Composition) ProtoMessage() {}

func (x *Composition) ProtoReflect() protoreflect.Message {
	mi := &file_glyph_proto_canvas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Composition.ProtoReflect.Descriptor instead.
func (*Composition) Descriptor() ([]byte, []int) {
	return file_glyph_proto_canvas_proto_rawDescGZIP(), []int{1}
}

func (x *Composition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Composition) GetEdges() []*CompositionEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Composition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Composition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_glyph_proto_canvas_proto protoreflect.FileDescriptor

const file_glyph_proto_canvas_proto_rawDesc = "" +
	"\n" +
	"\x18glyph/proto/canvas.proto\x12\x05glyph\"o\n" +
	"\x0fCompositionEdge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"m\n" +
	"\vComposition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x05edges\x18\x02 \x03(\v2\x16.glyph.CompositionEdgeR\x05edges\x12\f\n" +
	"\x01x\x18\x04 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x01R\x01yJ\x04\b\x03\x10\x04B%Z#github.com/teranos/QNTX/glyph/protob\x06proto3"

var (
	file_glyph_proto_canvas_proto_rawDescOnce sync.Once
	file_glyph_proto_canvas_proto_rawDescData []byte
)

func file_glyph_proto_canvas_proto_rawDescGZIP() []byte {
	file_glyph_proto_canvas_proto_rawDescOnce.Do(func() {
		file_glyph_proto_canvas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_glyph_proto_canvas_proto_rawDesc), len(file_glyph_proto_canvas_proto_rawDesc)))
	})
	return file_glyph_proto_canvas_proto_rawDescData
}

var file_glyph_proto_canvas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_glyph_proto_canvas_proto_goTypes = []any{
	(*CompositionEdge)(nil), // 0: glyph.CompositionEdge
	(*Composition)(nil),     // 1: glyph.Composition
}
var file_glyph_proto_canvas_proto_depIdxs = []int32{
	0, // 0: glyph.Composition.edges:type_name -> glyph.CompositionEdge
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_glyph_proto_canvas_proto_init() }
func file_glyph_proto_canvas_proto_init() {
	if File_glyph_proto_canvas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_glyph_proto_canvas_proto_rawDesc), len(file_glyph_proto_canvas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_glyph_proto_canvas_proto_goTypes,
		DependencyIndexes: file_glyph_proto_canvas_proto_depIdxs,
		MessageInfos:      file_glyph_proto_canvas_proto_msgTypes,
	}.Build()
	File_glyph_proto_canvas_proto = out.File
	file_glyph_proto_canvas_proto_goTypes = nil
	file_glyph_proto_canvas_proto_depIdxs = nil
}
