//! gRPC plugin infrastructure for QNTX plugins.
//!
//! Provides common scaffolding for building QNTX plugins:
//! - Server setup with graceful shutdown
//! - Proto definitions (compiled from plugin/grpc/protocol/)
//! - Common service patterns

mod server;
mod shutdown;

pub mod proto {
    //! Protobuf definitions and gRPC services.
    //! Types come from qntx-proto, services are generated by tonic.

    // Re-export all types from qntx-proto
    pub use qntx_proto::protocol::*;

    // Include gRPC service definitions generated by tonic
    // (types are referenced via extern_path to qntx_proto)
    tonic::include_proto!("protocol");
}

pub use server::PluginServer;
pub use shutdown::shutdown_signal;
