(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: plugin/grpc/protocol/github.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Protocol : sig
  module rec GitHubRateLimitRequest : sig
    type t = {
      auth_token:string;
      source:string;
      (**
{%html:
<p>The plugin asking.</p>
%}
      *)

      namespace:string;
      (**
{%html:
<p>Whose GitHub it is.</p>
%}
      *)

    }
    val make: ?auth_token:string -> ?source:string -> ?namespace:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?source:string -> ?namespace:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>GitHubRate is one of GitHub's rate limit resources, as GitHub states it.</p>
%}
  *)
  and GitHubRate : sig
    type t = {
      resource:string;
      (**
{%html:
<p>core, search, graphql, …</p>
%}
      *)

      limit:int;
      remaining:int;
      used:int;
      reset:int;
      (**
{%html:
<p>Unix seconds at which remaining is back to limit.</p>
%}
      *)

    }
    val make: ?resource:string -> ?limit:int -> ?remaining:int -> ?used:int -> ?reset:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?resource:string -> ?limit:int -> ?remaining:int -> ?used:int -> ?reset:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GitHubRateLimitResponse : sig
    type t = {
      success:bool;
      error:string;
      rates:GitHubRate.t list;
    }
    val make: ?success:bool -> ?error:string -> ?rates:GitHubRate.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?rates:GitHubRate.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  module GitHubService : sig
    module RateLimit : sig
      include Runtime'.Service.Rpc with type Request.t = GitHubRateLimitRequest.t and type Response.t = GitHubRateLimitResponse.t
      module Request : Runtime'.Spec.Message with type t = GitHubRateLimitRequest.t and type make_t = GitHubRateLimitRequest.make_t
      (** Module alias for the request message for this method call *)

      module Response : Runtime'.Spec.Message with type t = GitHubRateLimitResponse.t and type make_t = GitHubRateLimitResponse.make_t
      (** Module alias for the response message for this method call *)

    end

    val rateLimit : (module Runtime'.Spec.Message with type t = GitHubRateLimitRequest.t) * (module Runtime'.Spec.Message with type t = GitHubRateLimitResponse.t)
  end

end = struct
  module rec GitHubRateLimitRequest : sig
    type t = {
      auth_token:string;
      source:string;
      (**
{%html:
<p>The plugin asking.</p>
%}
      *)

      namespace:string;
      (**
{%html:
<p>Whose GitHub it is.</p>
%}
      *)

    }
    val make: ?auth_token:string -> ?source:string -> ?namespace:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?source:string -> ?namespace:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubRateLimitRequest
    let name () = ".protocol.GitHubRateLimitRequest"
    type t = {
      auth_token:string;
      source:string;
      namespace:string;
    }
    type make_t = ?auth_token:string -> ?source:string -> ?namespace:string -> unit -> t
    let make ?(auth_token = {||}) ?(source = {||}) ?(namespace = {||}) () = { auth_token; source; namespace }
    let merge =
    let merge_auth_token = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ) in
    let merge_source = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "source", "source"), string, ({||})) ) in
    let merge_namespace = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "namespace", "namespace"), string, ({||})) ) in
    fun t1 t2 -> {
    	auth_token = (merge_auth_token t1.auth_token t2.auth_token);
    	source = (merge_source t1.source t2.source);
    	namespace = (merge_namespace t1.namespace t2.namespace);
     }
    let spec () = Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ^:: basic ((2, "source", "source"), string, ({||})) ^:: basic ((3, "namespace", "namespace"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { auth_token; source; namespace } -> serialize writer auth_token source namespace

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor auth_token source namespace = { auth_token; source; namespace } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { auth_token; source; namespace } -> serialize auth_token source namespace
    let from_json_exn =
      let constructor auth_token source namespace = { auth_token; source; namespace } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubRate : sig
    type t = {
      resource:string;
      (**
{%html:
<p>core, search, graphql, …</p>
%}
      *)

      limit:int;
      remaining:int;
      used:int;
      reset:int;
      (**
{%html:
<p>Unix seconds at which remaining is back to limit.</p>
%}
      *)

    }
    val make: ?resource:string -> ?limit:int -> ?remaining:int -> ?used:int -> ?reset:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?resource:string -> ?limit:int -> ?remaining:int -> ?used:int -> ?reset:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubRate
    let name () = ".protocol.GitHubRate"
    type t = {
      resource:string;
      limit:int;
      remaining:int;
      used:int;
      reset:int;
    }
    type make_t = ?resource:string -> ?limit:int -> ?remaining:int -> ?used:int -> ?reset:int -> unit -> t
    let make ?(resource = {||}) ?(limit = 0) ?(remaining = 0) ?(used = 0) ?(reset = 0) () = { resource; limit; remaining; used; reset }
    let merge =
    let merge_resource = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "resource", "resource"), string, ({||})) ) in
    let merge_limit = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "limit", "limit"), int64_int, (0)) ) in
    let merge_remaining = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "remaining", "remaining"), int64_int, (0)) ) in
    let merge_used = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "used", "used"), int64_int, (0)) ) in
    let merge_reset = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "reset", "reset"), int64_int, (0)) ) in
    fun t1 t2 -> {
    	resource = (merge_resource t1.resource t2.resource);
    	limit = (merge_limit t1.limit t2.limit);
    	remaining = (merge_remaining t1.remaining t2.remaining);
    	used = (merge_used t1.used t2.used);
    	reset = (merge_reset t1.reset t2.reset);
     }
    let spec () = Runtime'.Spec.( basic ((1, "resource", "resource"), string, ({||})) ^:: basic ((2, "limit", "limit"), int64_int, (0)) ^:: basic ((3, "remaining", "remaining"), int64_int, (0)) ^:: basic ((4, "used", "used"), int64_int, (0)) ^:: basic ((5, "reset", "reset"), int64_int, (0)) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { resource; limit; remaining; used; reset } -> serialize writer resource limit remaining used reset

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor resource limit remaining used reset = { resource; limit; remaining; used; reset } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { resource; limit; remaining; used; reset } -> serialize resource limit remaining used reset
    let from_json_exn =
      let constructor resource limit remaining used reset = { resource; limit; remaining; used; reset } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubRateLimitResponse : sig
    type t = {
      success:bool;
      error:string;
      rates:GitHubRate.t list;
    }
    val make: ?success:bool -> ?error:string -> ?rates:GitHubRate.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?rates:GitHubRate.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubRateLimitResponse
    let name () = ".protocol.GitHubRateLimitResponse"
    type t = {
      success:bool;
      error:string;
      rates:GitHubRate.t list;
    }
    type make_t = ?success:bool -> ?error:string -> ?rates:GitHubRate.t list -> unit -> t
    let make ?(success = false) ?(error = {||}) ?(rates = []) () = { success; error; rates }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    let merge_rates = Runtime'.Merge.merge Runtime'.Spec.( repeated ((3, "rates", "rates"), (message (module GitHubRate)), not_packed) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
    	rates = (merge_rates t1.rates t2.rates);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: repeated ((3, "rates", "rates"), (message (module GitHubRate)), not_packed) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error; rates } -> serialize writer success error rates

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error rates = { success; error; rates } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error; rates } -> serialize success error rates
    let from_json_exn =
      let constructor success error rates = { success; error; rates } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  module GitHubService = struct
    module RateLimit = struct
      let package_name = Some "protocol"
      let service_name = "GitHubService"
      let method_name = "RateLimit"
      let name = "/protocol.GitHubService/RateLimit"
      module Request = GitHubRateLimitRequest
      module Response = GitHubRateLimitResponse
    end

    let rateLimit =
      (module GitHubRateLimitRequest : Runtime'.Spec.Message with type t = GitHubRateLimitRequest.t ),
      (module GitHubRateLimitResponse : Runtime'.Spec.Message with type t = GitHubRateLimitResponse.t )

  end

end

