(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: plugin/grpc/protocol/github_actions_workflow_jobs.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Protocol : sig

  (**
{%html:
<p>GET /repos/{owner}/{repo}/actions/jobs/{job_id}</p>
<p>ADR-043
https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2026-03-10</p>
%}
  *)
  module rec GitHubGetAJobForAWorkflowRunRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      job_id:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GitHubGetAJobForAWorkflowRunResponse : sig
    type t = {
      success:bool;
      error:string;
      id:int;
      run_id:int;
      run_url:string;
      run_attempt:int;
      node_id:string;
      head_sha:string;
      url:string;
      html_url:string;
      status:string;
      conclusion:string;
      created_at:string;
      started_at:string;
      completed_at:string;
      name:string;
      steps:GitHubActionsWorkflowJobsJob.Steps.t list;
      check_run_url:string;
      labels:string list;
      runner_id:int;
      runner_name:string;
      runner_group_id:int;
      runner_group_name:string;
      workflow_name:string;
      head_branch:string;
    }
    val make: ?success:bool -> ?error:string -> ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:GitHubActionsWorkflowJobsJob.Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:GitHubActionsWorkflowJobsJob.Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>GET /repos/{owner}/{repo}/actions/jobs/{job_id}/logs</p>
%}
  *)
  and GitHubDownloadJobLogsForAWorkflowRunRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      job_id:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GitHubDownloadJobLogsForAWorkflowRunResponse : sig
    type t = {
      success:bool;
      error:string;
      location:string;
      (**
{%html:
<p>&quot;Look for Location: in the response header to find the URL for the download.&quot;</p>
%}
      *)

    }
    val make: ?success:bool -> ?error:string -> ?location:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?location:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>GET /repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs</p>
%}
  *)
  and GitHubListJobsForAWorkflowRunAttemptRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      run_id:int;
      attempt_number:int;
      per_page:int;
      page:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?attempt_number:int -> ?per_page:int -> ?page:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?attempt_number:int -> ?per_page:int -> ?page:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GitHubListJobsForAWorkflowRunAttemptResponse : sig
    type t = {
      success:bool;
      error:string;
      total_count:int;
      jobs:GitHubActionsWorkflowJobsJob.t list;
    }
    val make: ?success:bool -> ?error:string -> ?total_count:int -> ?jobs:GitHubActionsWorkflowJobsJob.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?total_count:int -> ?jobs:GitHubActionsWorkflowJobsJob.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs
Response: same response schema as List jobs for a workflow run attempt.</p>
%}
  *)
  and GitHubListJobsForAWorkflowRunRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      run_id:int;
      filter:string;
      per_page:int;
      page:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?filter:string -> ?per_page:int -> ?page:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?filter:string -> ?per_page:int -> ?page:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>Job</p>
%}
  *)
  and GitHubActionsWorkflowJobsJob : sig
    module rec Steps : sig
      type t = {
        status:string;
        conclusion:string;
        name:string;
        number:int;
        started_at:string;
        completed_at:string;
      }
      val make: ?status:string -> ?conclusion:string -> ?name:string -> ?number:int -> ?started_at:string -> ?completed_at:string -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?status:string -> ?conclusion:string -> ?name:string -> ?number:int -> ?started_at:string -> ?completed_at:string -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    type t = {
      id:int;
      run_id:int;
      run_url:string;
      run_attempt:int;
      node_id:string;
      head_sha:string;
      url:string;
      html_url:string;
      status:string;
      conclusion:string;
      created_at:string;
      started_at:string;
      completed_at:string;
      name:string;
      steps:Steps.t list;
      check_run_url:string;
      labels:string list;
      runner_id:int;
      runner_name:string;
      runner_group_id:int;
      runner_group_name:string;
      workflow_name:string;
      head_branch:string;
    }
    val make: ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

end = struct
  module rec GitHubGetAJobForAWorkflowRunRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      job_id:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubGetAJobForAWorkflowRunRequest
    let name () = ".protocol.GitHubGetAJobForAWorkflowRunRequest"
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      job_id:int;
    }
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    let make ?(namespace = {||}) ?(owner = {||}) ?(repo = {||}) ?(job_id = 0) () = { namespace; owner; repo; job_id }
    let merge =
    let merge_namespace = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ) in
    let merge_owner = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "owner", "owner"), string, ({||})) ) in
    let merge_repo = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "repo", "repo"), string, ({||})) ) in
    let merge_job_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "job_id", "jobId"), int64_int, (0)) ) in
    fun t1 t2 -> {
    	namespace = (merge_namespace t1.namespace t2.namespace);
    	owner = (merge_owner t1.owner t2.owner);
    	repo = (merge_repo t1.repo t2.repo);
    	job_id = (merge_job_id t1.job_id t2.job_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ^:: basic ((2, "owner", "owner"), string, ({||})) ^:: basic ((3, "repo", "repo"), string, ({||})) ^:: basic ((4, "job_id", "jobId"), int64_int, (0)) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { namespace; owner; repo; job_id } -> serialize writer namespace owner repo job_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor namespace owner repo job_id = { namespace; owner; repo; job_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { namespace; owner; repo; job_id } -> serialize namespace owner repo job_id
    let from_json_exn =
      let constructor namespace owner repo job_id = { namespace; owner; repo; job_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubGetAJobForAWorkflowRunResponse : sig
    type t = {
      success:bool;
      error:string;
      id:int;
      run_id:int;
      run_url:string;
      run_attempt:int;
      node_id:string;
      head_sha:string;
      url:string;
      html_url:string;
      status:string;
      conclusion:string;
      created_at:string;
      started_at:string;
      completed_at:string;
      name:string;
      steps:GitHubActionsWorkflowJobsJob.Steps.t list;
      check_run_url:string;
      labels:string list;
      runner_id:int;
      runner_name:string;
      runner_group_id:int;
      runner_group_name:string;
      workflow_name:string;
      head_branch:string;
    }
    val make: ?success:bool -> ?error:string -> ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:GitHubActionsWorkflowJobsJob.Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:GitHubActionsWorkflowJobsJob.Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubGetAJobForAWorkflowRunResponse
    let name () = ".protocol.GitHubGetAJobForAWorkflowRunResponse"
    type t = {
      success:bool;
      error:string;
      id:int;
      run_id:int;
      run_url:string;
      run_attempt:int;
      node_id:string;
      head_sha:string;
      url:string;
      html_url:string;
      status:string;
      conclusion:string;
      created_at:string;
      started_at:string;
      completed_at:string;
      name:string;
      steps:GitHubActionsWorkflowJobsJob.Steps.t list;
      check_run_url:string;
      labels:string list;
      runner_id:int;
      runner_name:string;
      runner_group_id:int;
      runner_group_name:string;
      workflow_name:string;
      head_branch:string;
    }
    type make_t = ?success:bool -> ?error:string -> ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:GitHubActionsWorkflowJobsJob.Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    let make ?(success = false) ?(error = {||}) ?(id = 0) ?(run_id = 0) ?(run_url = {||}) ?(run_attempt = 0) ?(node_id = {||}) ?(head_sha = {||}) ?(url = {||}) ?(html_url = {||}) ?(status = {||}) ?(conclusion = {||}) ?(created_at = {||}) ?(started_at = {||}) ?(completed_at = {||}) ?(name = {||}) ?(steps = []) ?(check_run_url = {||}) ?(labels = []) ?(runner_id = 0) ?(runner_name = {||}) ?(runner_group_id = 0) ?(runner_group_name = {||}) ?(workflow_name = {||}) ?(head_branch = {||}) () = { success; error; id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    let merge_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "id", "id"), int64_int, (0)) ) in
    let merge_run_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "run_id", "runId"), int64_int, (0)) ) in
    let merge_run_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "run_url", "runUrl"), string, ({||})) ) in
    let merge_run_attempt = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "run_attempt", "runAttempt"), int64_int, (0)) ) in
    let merge_node_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "node_id", "nodeId"), string, ({||})) ) in
    let merge_head_sha = Runtime'.Merge.merge Runtime'.Spec.( basic ((8, "head_sha", "headSha"), string, ({||})) ) in
    let merge_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((9, "url", "url"), string, ({||})) ) in
    let merge_html_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((10, "html_url", "htmlUrl"), string, ({||})) ) in
    let merge_status = Runtime'.Merge.merge Runtime'.Spec.( basic ((11, "status", "status"), string, ({||})) ) in
    let merge_conclusion = Runtime'.Merge.merge Runtime'.Spec.( basic ((12, "conclusion", "conclusion"), string, ({||})) ) in
    let merge_created_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((13, "created_at", "createdAt"), string, ({||})) ) in
    let merge_started_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((14, "started_at", "startedAt"), string, ({||})) ) in
    let merge_completed_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((15, "completed_at", "completedAt"), string, ({||})) ) in
    let merge_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((16, "name", "name"), string, ({||})) ) in
    let merge_steps = Runtime'.Merge.merge Runtime'.Spec.( repeated ((17, "steps", "steps"), (message (module GitHubActionsWorkflowJobsJob.Steps)), not_packed) ) in
    let merge_check_run_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((18, "check_run_url", "checkRunUrl"), string, ({||})) ) in
    let merge_labels = Runtime'.Merge.merge Runtime'.Spec.( repeated ((19, "labels", "labels"), string, not_packed) ) in
    let merge_runner_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((20, "runner_id", "runnerId"), int64_int, (0)) ) in
    let merge_runner_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((21, "runner_name", "runnerName"), string, ({||})) ) in
    let merge_runner_group_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((22, "runner_group_id", "runnerGroupId"), int64_int, (0)) ) in
    let merge_runner_group_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((23, "runner_group_name", "runnerGroupName"), string, ({||})) ) in
    let merge_workflow_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((24, "workflow_name", "workflowName"), string, ({||})) ) in
    let merge_head_branch = Runtime'.Merge.merge Runtime'.Spec.( basic ((25, "head_branch", "headBranch"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
    	id = (merge_id t1.id t2.id);
    	run_id = (merge_run_id t1.run_id t2.run_id);
    	run_url = (merge_run_url t1.run_url t2.run_url);
    	run_attempt = (merge_run_attempt t1.run_attempt t2.run_attempt);
    	node_id = (merge_node_id t1.node_id t2.node_id);
    	head_sha = (merge_head_sha t1.head_sha t2.head_sha);
    	url = (merge_url t1.url t2.url);
    	html_url = (merge_html_url t1.html_url t2.html_url);
    	status = (merge_status t1.status t2.status);
    	conclusion = (merge_conclusion t1.conclusion t2.conclusion);
    	created_at = (merge_created_at t1.created_at t2.created_at);
    	started_at = (merge_started_at t1.started_at t2.started_at);
    	completed_at = (merge_completed_at t1.completed_at t2.completed_at);
    	name = (merge_name t1.name t2.name);
    	steps = (merge_steps t1.steps t2.steps);
    	check_run_url = (merge_check_run_url t1.check_run_url t2.check_run_url);
    	labels = (merge_labels t1.labels t2.labels);
    	runner_id = (merge_runner_id t1.runner_id t2.runner_id);
    	runner_name = (merge_runner_name t1.runner_name t2.runner_name);
    	runner_group_id = (merge_runner_group_id t1.runner_group_id t2.runner_group_id);
    	runner_group_name = (merge_runner_group_name t1.runner_group_name t2.runner_group_name);
    	workflow_name = (merge_workflow_name t1.workflow_name t2.workflow_name);
    	head_branch = (merge_head_branch t1.head_branch t2.head_branch);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: basic ((3, "id", "id"), int64_int, (0)) ^:: basic ((4, "run_id", "runId"), int64_int, (0)) ^:: basic ((5, "run_url", "runUrl"), string, ({||})) ^:: basic ((6, "run_attempt", "runAttempt"), int64_int, (0)) ^:: basic ((7, "node_id", "nodeId"), string, ({||})) ^:: basic ((8, "head_sha", "headSha"), string, ({||})) ^:: basic ((9, "url", "url"), string, ({||})) ^:: basic ((10, "html_url", "htmlUrl"), string, ({||})) ^:: basic ((11, "status", "status"), string, ({||})) ^:: basic ((12, "conclusion", "conclusion"), string, ({||})) ^:: basic ((13, "created_at", "createdAt"), string, ({||})) ^:: basic ((14, "started_at", "startedAt"), string, ({||})) ^:: basic ((15, "completed_at", "completedAt"), string, ({||})) ^:: basic ((16, "name", "name"), string, ({||})) ^:: repeated ((17, "steps", "steps"), (message (module GitHubActionsWorkflowJobsJob.Steps)), not_packed) ^:: basic ((18, "check_run_url", "checkRunUrl"), string, ({||})) ^:: repeated ((19, "labels", "labels"), string, not_packed) ^:: basic ((20, "runner_id", "runnerId"), int64_int, (0)) ^:: basic ((21, "runner_name", "runnerName"), string, ({||})) ^:: basic ((22, "runner_group_id", "runnerGroupId"), int64_int, (0)) ^:: basic ((23, "runner_group_name", "runnerGroupName"), string, ({||})) ^:: basic ((24, "workflow_name", "workflowName"), string, ({||})) ^:: basic ((25, "head_branch", "headBranch"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error; id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } -> serialize writer success error id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch = { success; error; id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error; id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } -> serialize success error id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch
    let from_json_exn =
      let constructor success error id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch = { success; error; id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubDownloadJobLogsForAWorkflowRunRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      job_id:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubDownloadJobLogsForAWorkflowRunRequest
    let name () = ".protocol.GitHubDownloadJobLogsForAWorkflowRunRequest"
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      job_id:int;
    }
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?job_id:int -> unit -> t
    let make ?(namespace = {||}) ?(owner = {||}) ?(repo = {||}) ?(job_id = 0) () = { namespace; owner; repo; job_id }
    let merge =
    let merge_namespace = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ) in
    let merge_owner = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "owner", "owner"), string, ({||})) ) in
    let merge_repo = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "repo", "repo"), string, ({||})) ) in
    let merge_job_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "job_id", "jobId"), int64_int, (0)) ) in
    fun t1 t2 -> {
    	namespace = (merge_namespace t1.namespace t2.namespace);
    	owner = (merge_owner t1.owner t2.owner);
    	repo = (merge_repo t1.repo t2.repo);
    	job_id = (merge_job_id t1.job_id t2.job_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ^:: basic ((2, "owner", "owner"), string, ({||})) ^:: basic ((3, "repo", "repo"), string, ({||})) ^:: basic ((4, "job_id", "jobId"), int64_int, (0)) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { namespace; owner; repo; job_id } -> serialize writer namespace owner repo job_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor namespace owner repo job_id = { namespace; owner; repo; job_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { namespace; owner; repo; job_id } -> serialize namespace owner repo job_id
    let from_json_exn =
      let constructor namespace owner repo job_id = { namespace; owner; repo; job_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubDownloadJobLogsForAWorkflowRunResponse : sig
    type t = {
      success:bool;
      error:string;
      location:string;
      (**
{%html:
<p>&quot;Look for Location: in the response header to find the URL for the download.&quot;</p>
%}
      *)

    }
    val make: ?success:bool -> ?error:string -> ?location:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?location:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubDownloadJobLogsForAWorkflowRunResponse
    let name () = ".protocol.GitHubDownloadJobLogsForAWorkflowRunResponse"
    type t = {
      success:bool;
      error:string;
      location:string;
    }
    type make_t = ?success:bool -> ?error:string -> ?location:string -> unit -> t
    let make ?(success = false) ?(error = {||}) ?(location = {||}) () = { success; error; location }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    let merge_location = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "location", "location"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
    	location = (merge_location t1.location t2.location);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: basic ((3, "location", "location"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error; location } -> serialize writer success error location

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error location = { success; error; location } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error; location } -> serialize success error location
    let from_json_exn =
      let constructor success error location = { success; error; location } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubListJobsForAWorkflowRunAttemptRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      run_id:int;
      attempt_number:int;
      per_page:int;
      page:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?attempt_number:int -> ?per_page:int -> ?page:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?attempt_number:int -> ?per_page:int -> ?page:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubListJobsForAWorkflowRunAttemptRequest
    let name () = ".protocol.GitHubListJobsForAWorkflowRunAttemptRequest"
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      run_id:int;
      attempt_number:int;
      per_page:int;
      page:int;
    }
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?attempt_number:int -> ?per_page:int -> ?page:int -> unit -> t
    let make ?(namespace = {||}) ?(owner = {||}) ?(repo = {||}) ?(run_id = 0) ?(attempt_number = 0) ?(per_page = 0) ?(page = 0) () = { namespace; owner; repo; run_id; attempt_number; per_page; page }
    let merge =
    let merge_namespace = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ) in
    let merge_owner = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "owner", "owner"), string, ({||})) ) in
    let merge_repo = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "repo", "repo"), string, ({||})) ) in
    let merge_run_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "run_id", "runId"), int64_int, (0)) ) in
    let merge_attempt_number = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "attempt_number", "attemptNumber"), int64_int, (0)) ) in
    let merge_per_page = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "per_page", "perPage"), int64_int, (0)) ) in
    let merge_page = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "page", "page"), int64_int, (0)) ) in
    fun t1 t2 -> {
    	namespace = (merge_namespace t1.namespace t2.namespace);
    	owner = (merge_owner t1.owner t2.owner);
    	repo = (merge_repo t1.repo t2.repo);
    	run_id = (merge_run_id t1.run_id t2.run_id);
    	attempt_number = (merge_attempt_number t1.attempt_number t2.attempt_number);
    	per_page = (merge_per_page t1.per_page t2.per_page);
    	page = (merge_page t1.page t2.page);
     }
    let spec () = Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ^:: basic ((2, "owner", "owner"), string, ({||})) ^:: basic ((3, "repo", "repo"), string, ({||})) ^:: basic ((4, "run_id", "runId"), int64_int, (0)) ^:: basic ((5, "attempt_number", "attemptNumber"), int64_int, (0)) ^:: basic ((6, "per_page", "perPage"), int64_int, (0)) ^:: basic ((7, "page", "page"), int64_int, (0)) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { namespace; owner; repo; run_id; attempt_number; per_page; page } -> serialize writer namespace owner repo run_id attempt_number per_page page

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor namespace owner repo run_id attempt_number per_page page = { namespace; owner; repo; run_id; attempt_number; per_page; page } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { namespace; owner; repo; run_id; attempt_number; per_page; page } -> serialize namespace owner repo run_id attempt_number per_page page
    let from_json_exn =
      let constructor namespace owner repo run_id attempt_number per_page page = { namespace; owner; repo; run_id; attempt_number; per_page; page } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubListJobsForAWorkflowRunAttemptResponse : sig
    type t = {
      success:bool;
      error:string;
      total_count:int;
      jobs:GitHubActionsWorkflowJobsJob.t list;
    }
    val make: ?success:bool -> ?error:string -> ?total_count:int -> ?jobs:GitHubActionsWorkflowJobsJob.t list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?total_count:int -> ?jobs:GitHubActionsWorkflowJobsJob.t list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubListJobsForAWorkflowRunAttemptResponse
    let name () = ".protocol.GitHubListJobsForAWorkflowRunAttemptResponse"
    type t = {
      success:bool;
      error:string;
      total_count:int;
      jobs:GitHubActionsWorkflowJobsJob.t list;
    }
    type make_t = ?success:bool -> ?error:string -> ?total_count:int -> ?jobs:GitHubActionsWorkflowJobsJob.t list -> unit -> t
    let make ?(success = false) ?(error = {||}) ?(total_count = 0) ?(jobs = []) () = { success; error; total_count; jobs }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    let merge_total_count = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "total_count", "totalCount"), int64_int, (0)) ) in
    let merge_jobs = Runtime'.Merge.merge Runtime'.Spec.( repeated ((4, "jobs", "jobs"), (message (module GitHubActionsWorkflowJobsJob)), not_packed) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
    	total_count = (merge_total_count t1.total_count t2.total_count);
    	jobs = (merge_jobs t1.jobs t2.jobs);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: basic ((3, "total_count", "totalCount"), int64_int, (0)) ^:: repeated ((4, "jobs", "jobs"), (message (module GitHubActionsWorkflowJobsJob)), not_packed) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error; total_count; jobs } -> serialize writer success error total_count jobs

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error total_count jobs = { success; error; total_count; jobs } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error; total_count; jobs } -> serialize success error total_count jobs
    let from_json_exn =
      let constructor success error total_count jobs = { success; error; total_count; jobs } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubListJobsForAWorkflowRunRequest : sig
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      run_id:int;
      filter:string;
      per_page:int;
      page:int;
    }
    val make: ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?filter:string -> ?per_page:int -> ?page:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?filter:string -> ?per_page:int -> ?page:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubListJobsForAWorkflowRunRequest
    let name () = ".protocol.GitHubListJobsForAWorkflowRunRequest"
    type t = {
      namespace:string;
      owner:string;
      repo:string;
      run_id:int;
      filter:string;
      per_page:int;
      page:int;
    }
    type make_t = ?namespace:string -> ?owner:string -> ?repo:string -> ?run_id:int -> ?filter:string -> ?per_page:int -> ?page:int -> unit -> t
    let make ?(namespace = {||}) ?(owner = {||}) ?(repo = {||}) ?(run_id = 0) ?(filter = {||}) ?(per_page = 0) ?(page = 0) () = { namespace; owner; repo; run_id; filter; per_page; page }
    let merge =
    let merge_namespace = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ) in
    let merge_owner = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "owner", "owner"), string, ({||})) ) in
    let merge_repo = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "repo", "repo"), string, ({||})) ) in
    let merge_run_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "run_id", "runId"), int64_int, (0)) ) in
    let merge_filter = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "filter", "filter"), string, ({||})) ) in
    let merge_per_page = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "per_page", "perPage"), int64_int, (0)) ) in
    let merge_page = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "page", "page"), int64_int, (0)) ) in
    fun t1 t2 -> {
    	namespace = (merge_namespace t1.namespace t2.namespace);
    	owner = (merge_owner t1.owner t2.owner);
    	repo = (merge_repo t1.repo t2.repo);
    	run_id = (merge_run_id t1.run_id t2.run_id);
    	filter = (merge_filter t1.filter t2.filter);
    	per_page = (merge_per_page t1.per_page t2.per_page);
    	page = (merge_page t1.page t2.page);
     }
    let spec () = Runtime'.Spec.( basic ((1, "namespace", "namespace"), string, ({||})) ^:: basic ((2, "owner", "owner"), string, ({||})) ^:: basic ((3, "repo", "repo"), string, ({||})) ^:: basic ((4, "run_id", "runId"), int64_int, (0)) ^:: basic ((5, "filter", "filter"), string, ({||})) ^:: basic ((6, "per_page", "perPage"), int64_int, (0)) ^:: basic ((7, "page", "page"), int64_int, (0)) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { namespace; owner; repo; run_id; filter; per_page; page } -> serialize writer namespace owner repo run_id filter per_page page

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor namespace owner repo run_id filter per_page page = { namespace; owner; repo; run_id; filter; per_page; page } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { namespace; owner; repo; run_id; filter; per_page; page } -> serialize namespace owner repo run_id filter per_page page
    let from_json_exn =
      let constructor namespace owner repo run_id filter per_page page = { namespace; owner; repo; run_id; filter; per_page; page } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubActionsWorkflowJobsJob : sig
    module rec Steps : sig
      type t = {
        status:string;
        conclusion:string;
        name:string;
        number:int;
        started_at:string;
        completed_at:string;
      }
      val make: ?status:string -> ?conclusion:string -> ?name:string -> ?number:int -> ?started_at:string -> ?completed_at:string -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?status:string -> ?conclusion:string -> ?name:string -> ?number:int -> ?started_at:string -> ?completed_at:string -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end

    type t = {
      id:int;
      run_id:int;
      run_url:string;
      run_attempt:int;
      node_id:string;
      head_sha:string;
      url:string;
      html_url:string;
      status:string;
      conclusion:string;
      created_at:string;
      started_at:string;
      completed_at:string;
      name:string;
      steps:Steps.t list;
      check_run_url:string;
      labels:string list;
      runner_id:int;
      runner_name:string;
      runner_group_id:int;
      runner_group_name:string;
      workflow_name:string;
      head_branch:string;
    }
    val make: ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubActionsWorkflowJobsJob
    module rec Steps : sig
      type t = {
        status:string;
        conclusion:string;
        name:string;
        number:int;
        started_at:string;
        completed_at:string;
      }
      val make: ?status:string -> ?conclusion:string -> ?name:string -> ?number:int -> ?started_at:string -> ?completed_at:string -> unit -> t
      (** Helper function to generate a message using default values *)

      val to_proto: t -> Runtime'.Writer.t
      (** Serialize the message to binary format *)

      val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from binary format *)

      val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
      (** Serialize to Json (compatible with Yojson.Basic.t) *)

      val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
      (** Deserialize from Json (compatible with Yojson.Basic.t) *)

      val name: unit -> string
      (** Fully qualified protobuf name of this message *)

      (**/**)
      type make_t = ?status:string -> ?conclusion:string -> ?name:string -> ?number:int -> ?started_at:string -> ?completed_at:string -> unit -> t
      val merge: t -> t -> t
      val to_proto': Runtime'.Writer.t -> t -> unit
      val from_proto_exn: Runtime'.Reader.t -> t
      val from_json_exn: Runtime'.Json.t -> t
      (**/**)
    end = struct
      module This'_ = Steps
      let name () = ".protocol.GitHubActionsWorkflowJobsJob.Steps"
      type t = {
        status:string;
        conclusion:string;
        name:string;
        number:int;
        started_at:string;
        completed_at:string;
      }
      type make_t = ?status:string -> ?conclusion:string -> ?name:string -> ?number:int -> ?started_at:string -> ?completed_at:string -> unit -> t
      let make ?(status = {||}) ?(conclusion = {||}) ?(name = {||}) ?(number = 0) ?(started_at = {||}) ?(completed_at = {||}) () = { status; conclusion; name; number; started_at; completed_at }
      let merge =
      let merge_status = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "status", "status"), string, ({||})) ) in
      let merge_conclusion = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "conclusion", "conclusion"), string, ({||})) ) in
      let merge_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "name", "name"), string, ({||})) ) in
      let merge_number = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "number", "number"), int64_int, (0)) ) in
      let merge_started_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "started_at", "startedAt"), string, ({||})) ) in
      let merge_completed_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "completed_at", "completedAt"), string, ({||})) ) in
      fun t1 t2 -> {
      	status = (merge_status t1.status t2.status);
      	conclusion = (merge_conclusion t1.conclusion t2.conclusion);
      	name = (merge_name t1.name t2.name);
      	number = (merge_number t1.number t2.number);
      	started_at = (merge_started_at t1.started_at t2.started_at);
      	completed_at = (merge_completed_at t1.completed_at t2.completed_at);
       }
      let spec () = Runtime'.Spec.( basic ((1, "status", "status"), string, ({||})) ^:: basic ((2, "conclusion", "conclusion"), string, ({||})) ^:: basic ((3, "name", "name"), string, ({||})) ^:: basic ((4, "number", "number"), int64_int, (0)) ^:: basic ((5, "started_at", "startedAt"), string, ({||})) ^:: basic ((6, "completed_at", "completedAt"), string, ({||})) ^:: nil )
      let to_proto' =
        let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
        fun writer { status; conclusion; name; number; started_at; completed_at } -> serialize writer status conclusion name number started_at completed_at

      let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
      let from_proto_exn =
        let constructor status conclusion name number started_at completed_at = { status; conclusion; name; number; started_at; completed_at } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
      let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
      let to_json options =
        let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
        fun { status; conclusion; name; number; started_at; completed_at } -> serialize status conclusion name number started_at completed_at
      let from_json_exn =
        let constructor status conclusion name number started_at completed_at = { status; conclusion; name; number; started_at; completed_at } in
        Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
      let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
    end

    let name () = ".protocol.GitHubActionsWorkflowJobsJob"
    type t = {
      id:int;
      run_id:int;
      run_url:string;
      run_attempt:int;
      node_id:string;
      head_sha:string;
      url:string;
      html_url:string;
      status:string;
      conclusion:string;
      created_at:string;
      started_at:string;
      completed_at:string;
      name:string;
      steps:Steps.t list;
      check_run_url:string;
      labels:string list;
      runner_id:int;
      runner_name:string;
      runner_group_id:int;
      runner_group_name:string;
      workflow_name:string;
      head_branch:string;
    }
    type make_t = ?id:int -> ?run_id:int -> ?run_url:string -> ?run_attempt:int -> ?node_id:string -> ?head_sha:string -> ?url:string -> ?html_url:string -> ?status:string -> ?conclusion:string -> ?created_at:string -> ?started_at:string -> ?completed_at:string -> ?name:string -> ?steps:Steps.t list -> ?check_run_url:string -> ?labels:string list -> ?runner_id:int -> ?runner_name:string -> ?runner_group_id:int -> ?runner_group_name:string -> ?workflow_name:string -> ?head_branch:string -> unit -> t
    let make ?(id = 0) ?(run_id = 0) ?(run_url = {||}) ?(run_attempt = 0) ?(node_id = {||}) ?(head_sha = {||}) ?(url = {||}) ?(html_url = {||}) ?(status = {||}) ?(conclusion = {||}) ?(created_at = {||}) ?(started_at = {||}) ?(completed_at = {||}) ?(name = {||}) ?(steps = []) ?(check_run_url = {||}) ?(labels = []) ?(runner_id = 0) ?(runner_name = {||}) ?(runner_group_id = 0) ?(runner_group_name = {||}) ?(workflow_name = {||}) ?(head_branch = {||}) () = { id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch }
    let merge =
    let merge_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "id", "id"), int64_int, (0)) ) in
    let merge_run_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "run_id", "runId"), int64_int, (0)) ) in
    let merge_run_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "run_url", "runUrl"), string, ({||})) ) in
    let merge_run_attempt = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "run_attempt", "runAttempt"), int64_int, (0)) ) in
    let merge_node_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "node_id", "nodeId"), string, ({||})) ) in
    let merge_head_sha = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "head_sha", "headSha"), string, ({||})) ) in
    let merge_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "url", "url"), string, ({||})) ) in
    let merge_html_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((8, "html_url", "htmlUrl"), string, ({||})) ) in
    let merge_status = Runtime'.Merge.merge Runtime'.Spec.( basic ((9, "status", "status"), string, ({||})) ) in
    let merge_conclusion = Runtime'.Merge.merge Runtime'.Spec.( basic ((10, "conclusion", "conclusion"), string, ({||})) ) in
    let merge_created_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((11, "created_at", "createdAt"), string, ({||})) ) in
    let merge_started_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((12, "started_at", "startedAt"), string, ({||})) ) in
    let merge_completed_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((13, "completed_at", "completedAt"), string, ({||})) ) in
    let merge_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((14, "name", "name"), string, ({||})) ) in
    let merge_steps = Runtime'.Merge.merge Runtime'.Spec.( repeated ((15, "steps", "steps"), (message (module Steps)), not_packed) ) in
    let merge_check_run_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((16, "check_run_url", "checkRunUrl"), string, ({||})) ) in
    let merge_labels = Runtime'.Merge.merge Runtime'.Spec.( repeated ((17, "labels", "labels"), string, not_packed) ) in
    let merge_runner_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((18, "runner_id", "runnerId"), int64_int, (0)) ) in
    let merge_runner_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((19, "runner_name", "runnerName"), string, ({||})) ) in
    let merge_runner_group_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((20, "runner_group_id", "runnerGroupId"), int64_int, (0)) ) in
    let merge_runner_group_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((21, "runner_group_name", "runnerGroupName"), string, ({||})) ) in
    let merge_workflow_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((22, "workflow_name", "workflowName"), string, ({||})) ) in
    let merge_head_branch = Runtime'.Merge.merge Runtime'.Spec.( basic ((23, "head_branch", "headBranch"), string, ({||})) ) in
    fun t1 t2 -> {
    	id = (merge_id t1.id t2.id);
    	run_id = (merge_run_id t1.run_id t2.run_id);
    	run_url = (merge_run_url t1.run_url t2.run_url);
    	run_attempt = (merge_run_attempt t1.run_attempt t2.run_attempt);
    	node_id = (merge_node_id t1.node_id t2.node_id);
    	head_sha = (merge_head_sha t1.head_sha t2.head_sha);
    	url = (merge_url t1.url t2.url);
    	html_url = (merge_html_url t1.html_url t2.html_url);
    	status = (merge_status t1.status t2.status);
    	conclusion = (merge_conclusion t1.conclusion t2.conclusion);
    	created_at = (merge_created_at t1.created_at t2.created_at);
    	started_at = (merge_started_at t1.started_at t2.started_at);
    	completed_at = (merge_completed_at t1.completed_at t2.completed_at);
    	name = (merge_name t1.name t2.name);
    	steps = (merge_steps t1.steps t2.steps);
    	check_run_url = (merge_check_run_url t1.check_run_url t2.check_run_url);
    	labels = (merge_labels t1.labels t2.labels);
    	runner_id = (merge_runner_id t1.runner_id t2.runner_id);
    	runner_name = (merge_runner_name t1.runner_name t2.runner_name);
    	runner_group_id = (merge_runner_group_id t1.runner_group_id t2.runner_group_id);
    	runner_group_name = (merge_runner_group_name t1.runner_group_name t2.runner_group_name);
    	workflow_name = (merge_workflow_name t1.workflow_name t2.workflow_name);
    	head_branch = (merge_head_branch t1.head_branch t2.head_branch);
     }
    let spec () = Runtime'.Spec.( basic ((1, "id", "id"), int64_int, (0)) ^:: basic ((2, "run_id", "runId"), int64_int, (0)) ^:: basic ((3, "run_url", "runUrl"), string, ({||})) ^:: basic ((4, "run_attempt", "runAttempt"), int64_int, (0)) ^:: basic ((5, "node_id", "nodeId"), string, ({||})) ^:: basic ((6, "head_sha", "headSha"), string, ({||})) ^:: basic ((7, "url", "url"), string, ({||})) ^:: basic ((8, "html_url", "htmlUrl"), string, ({||})) ^:: basic ((9, "status", "status"), string, ({||})) ^:: basic ((10, "conclusion", "conclusion"), string, ({||})) ^:: basic ((11, "created_at", "createdAt"), string, ({||})) ^:: basic ((12, "started_at", "startedAt"), string, ({||})) ^:: basic ((13, "completed_at", "completedAt"), string, ({||})) ^:: basic ((14, "name", "name"), string, ({||})) ^:: repeated ((15, "steps", "steps"), (message (module Steps)), not_packed) ^:: basic ((16, "check_run_url", "checkRunUrl"), string, ({||})) ^:: repeated ((17, "labels", "labels"), string, not_packed) ^:: basic ((18, "runner_id", "runnerId"), int64_int, (0)) ^:: basic ((19, "runner_name", "runnerName"), string, ({||})) ^:: basic ((20, "runner_group_id", "runnerGroupId"), int64_int, (0)) ^:: basic ((21, "runner_group_name", "runnerGroupName"), string, ({||})) ^:: basic ((22, "workflow_name", "workflowName"), string, ({||})) ^:: basic ((23, "head_branch", "headBranch"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } -> serialize writer id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch = { id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } -> serialize id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch
    let from_json_exn =
      let constructor id run_id run_url run_attempt node_id head_sha url html_url status conclusion created_at started_at completed_at name steps check_run_url labels runner_id runner_name runner_group_id runner_group_name workflow_name head_branch = { id; run_id; run_url; run_attempt; node_id; head_sha; url; html_url; status; conclusion; created_at; started_at; completed_at; name; steps; check_run_url; labels; runner_id; runner_name; runner_group_id; runner_group_name; workflow_name; head_branch } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

end

