(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: plugin/grpc/protocol/github_apps_webhooks.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Protocol : sig

  (**
{%html:
<p>GET /app/hook/deliveries</p>
<p>ADR-043
https://docs.github.com/en/rest/apps/webhooks?apiVersion=2026-03-10
Both are the App's own: GitHub takes them only with a JWT the App signs.</p>
%}
  *)
  module rec GitHubListDeliveriesForAnAppWebhookRequest : sig
    type t = {
      per_page:int;
      cursor:string;
      status:string;
    }
    val make: ?per_page:int -> ?cursor:string -> ?status:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?per_page:int -> ?cursor:string -> ?status:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GitHubListDeliveriesForAnAppWebhookResponse : sig
    type t = {
      success:bool;
      error:string;
      items:GitHubAppsWebhooksHookDeliveryItem.t list;
      link:string;
      (**
{%html:
<p>&quot;Refer to the <code>link</code> header for the next and previous page cursors.&quot;</p>
%}
      *)

    }
    val make: ?success:bool -> ?error:string -> ?items:GitHubAppsWebhooksHookDeliveryItem.t list -> ?link:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?items:GitHubAppsWebhooksHookDeliveryItem.t list -> ?link:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>POST /app/hook/deliveries/{delivery_id}/attempts</p>
%}
  *)
  and GitHubRedeliverADeliveryForAnAppWebhookRequest : sig
    type t = (int)
    val make: ?delivery_id:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?delivery_id:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GitHubRedeliverADeliveryForAnAppWebhookResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end


  (**
{%html:
<p>Simple webhook delivery</p>
%}
  *)
  and GitHubAppsWebhooksHookDeliveryItem : sig
    type t = {
      id:int;
      guid:string;
      delivered_at:string;
      redelivery:bool;
      duration:float;
      status:string;
      status_code:int;
      event:string;
      action:string;
      installation_id:int;
      repository_id:int;
      throttled_at:string;
    }
    val make: ?id:int -> ?guid:string -> ?delivered_at:string -> ?redelivery:bool -> ?duration:float -> ?status:string -> ?status_code:int -> ?event:string -> ?action:string -> ?installation_id:int -> ?repository_id:int -> ?throttled_at:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:int -> ?guid:string -> ?delivered_at:string -> ?redelivery:bool -> ?duration:float -> ?status:string -> ?status_code:int -> ?event:string -> ?action:string -> ?installation_id:int -> ?repository_id:int -> ?throttled_at:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

end = struct
  module rec GitHubListDeliveriesForAnAppWebhookRequest : sig
    type t = {
      per_page:int;
      cursor:string;
      status:string;
    }
    val make: ?per_page:int -> ?cursor:string -> ?status:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?per_page:int -> ?cursor:string -> ?status:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubListDeliveriesForAnAppWebhookRequest
    let name () = ".protocol.GitHubListDeliveriesForAnAppWebhookRequest"
    type t = {
      per_page:int;
      cursor:string;
      status:string;
    }
    type make_t = ?per_page:int -> ?cursor:string -> ?status:string -> unit -> t
    let make ?(per_page = 0) ?(cursor = {||}) ?(status = {||}) () = { per_page; cursor; status }
    let merge =
    let merge_per_page = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "per_page", "perPage"), int64_int, (0)) ) in
    let merge_cursor = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "cursor", "cursor"), string, ({||})) ) in
    let merge_status = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "status", "status"), string, ({||})) ) in
    fun t1 t2 -> {
    	per_page = (merge_per_page t1.per_page t2.per_page);
    	cursor = (merge_cursor t1.cursor t2.cursor);
    	status = (merge_status t1.status t2.status);
     }
    let spec () = Runtime'.Spec.( basic ((1, "per_page", "perPage"), int64_int, (0)) ^:: basic ((2, "cursor", "cursor"), string, ({||})) ^:: basic ((3, "status", "status"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { per_page; cursor; status } -> serialize writer per_page cursor status

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor per_page cursor status = { per_page; cursor; status } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { per_page; cursor; status } -> serialize per_page cursor status
    let from_json_exn =
      let constructor per_page cursor status = { per_page; cursor; status } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubListDeliveriesForAnAppWebhookResponse : sig
    type t = {
      success:bool;
      error:string;
      items:GitHubAppsWebhooksHookDeliveryItem.t list;
      link:string;
      (**
{%html:
<p>&quot;Refer to the <code>link</code> header for the next and previous page cursors.&quot;</p>
%}
      *)

    }
    val make: ?success:bool -> ?error:string -> ?items:GitHubAppsWebhooksHookDeliveryItem.t list -> ?link:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?items:GitHubAppsWebhooksHookDeliveryItem.t list -> ?link:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubListDeliveriesForAnAppWebhookResponse
    let name () = ".protocol.GitHubListDeliveriesForAnAppWebhookResponse"
    type t = {
      success:bool;
      error:string;
      items:GitHubAppsWebhooksHookDeliveryItem.t list;
      link:string;
    }
    type make_t = ?success:bool -> ?error:string -> ?items:GitHubAppsWebhooksHookDeliveryItem.t list -> ?link:string -> unit -> t
    let make ?(success = false) ?(error = {||}) ?(items = []) ?(link = {||}) () = { success; error; items; link }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    let merge_items = Runtime'.Merge.merge Runtime'.Spec.( repeated ((3, "items", "items"), (message (module GitHubAppsWebhooksHookDeliveryItem)), not_packed) ) in
    let merge_link = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "link", "link"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
    	items = (merge_items t1.items t2.items);
    	link = (merge_link t1.link t2.link);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: repeated ((3, "items", "items"), (message (module GitHubAppsWebhooksHookDeliveryItem)), not_packed) ^:: basic ((4, "link", "link"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error; items; link } -> serialize writer success error items link

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error items link = { success; error; items; link } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error; items; link } -> serialize success error items link
    let from_json_exn =
      let constructor success error items link = { success; error; items; link } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubRedeliverADeliveryForAnAppWebhookRequest : sig
    type t = (int)
    val make: ?delivery_id:int -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?delivery_id:int -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubRedeliverADeliveryForAnAppWebhookRequest
    let name () = ".protocol.GitHubRedeliverADeliveryForAnAppWebhookRequest"
    type t = (int)
    type make_t = ?delivery_id:int -> unit -> t
    let make ?(delivery_id = 0) () = (delivery_id)
    let merge =
    let merge_delivery_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "delivery_id", "deliveryId"), int64_int, (0)) ) in
    fun (t1_delivery_id) (t2_delivery_id) -> merge_delivery_id t1_delivery_id t2_delivery_id
    let spec () = Runtime'.Spec.( basic ((1, "delivery_id", "deliveryId"), int64_int, (0)) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer (delivery_id) -> serialize writer delivery_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor delivery_id = (delivery_id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun (delivery_id) -> serialize delivery_id
    let from_json_exn =
      let constructor delivery_id = (delivery_id) in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubRedeliverADeliveryForAnAppWebhookResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubRedeliverADeliveryForAnAppWebhookResponse
    let name () = ".protocol.GitHubRedeliverADeliveryForAnAppWebhookResponse"
    type t = {
      success:bool;
      error:string;
    }
    type make_t = ?success:bool -> ?error:string -> unit -> t
    let make ?(success = false) ?(error = {||}) () = { success; error }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error } -> serialize writer success error

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error } -> serialize success error
    let from_json_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GitHubAppsWebhooksHookDeliveryItem : sig
    type t = {
      id:int;
      guid:string;
      delivered_at:string;
      redelivery:bool;
      duration:float;
      status:string;
      status_code:int;
      event:string;
      action:string;
      installation_id:int;
      repository_id:int;
      throttled_at:string;
    }
    val make: ?id:int -> ?guid:string -> ?delivered_at:string -> ?redelivery:bool -> ?duration:float -> ?status:string -> ?status_code:int -> ?event:string -> ?action:string -> ?installation_id:int -> ?repository_id:int -> ?throttled_at:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:int -> ?guid:string -> ?delivered_at:string -> ?redelivery:bool -> ?duration:float -> ?status:string -> ?status_code:int -> ?event:string -> ?action:string -> ?installation_id:int -> ?repository_id:int -> ?throttled_at:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GitHubAppsWebhooksHookDeliveryItem
    let name () = ".protocol.GitHubAppsWebhooksHookDeliveryItem"
    type t = {
      id:int;
      guid:string;
      delivered_at:string;
      redelivery:bool;
      duration:float;
      status:string;
      status_code:int;
      event:string;
      action:string;
      installation_id:int;
      repository_id:int;
      throttled_at:string;
    }
    type make_t = ?id:int -> ?guid:string -> ?delivered_at:string -> ?redelivery:bool -> ?duration:float -> ?status:string -> ?status_code:int -> ?event:string -> ?action:string -> ?installation_id:int -> ?repository_id:int -> ?throttled_at:string -> unit -> t
    let make ?(id = 0) ?(guid = {||}) ?(delivered_at = {||}) ?(redelivery = false) ?(duration = 0.) ?(status = {||}) ?(status_code = 0) ?(event = {||}) ?(action = {||}) ?(installation_id = 0) ?(repository_id = 0) ?(throttled_at = {||}) () = { id; guid; delivered_at; redelivery; duration; status; status_code; event; action; installation_id; repository_id; throttled_at }
    let merge =
    let merge_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "id", "id"), int64_int, (0)) ) in
    let merge_guid = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "guid", "guid"), string, ({||})) ) in
    let merge_delivered_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "delivered_at", "deliveredAt"), string, ({||})) ) in
    let merge_redelivery = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "redelivery", "redelivery"), bool, (false)) ) in
    let merge_duration = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "duration", "duration"), double, (0.)) ) in
    let merge_status = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "status", "status"), string, ({||})) ) in
    let merge_status_code = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "status_code", "statusCode"), int64_int, (0)) ) in
    let merge_event = Runtime'.Merge.merge Runtime'.Spec.( basic ((8, "event", "event"), string, ({||})) ) in
    let merge_action = Runtime'.Merge.merge Runtime'.Spec.( basic ((9, "action", "action"), string, ({||})) ) in
    let merge_installation_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((10, "installation_id", "installationId"), int64_int, (0)) ) in
    let merge_repository_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((11, "repository_id", "repositoryId"), int64_int, (0)) ) in
    let merge_throttled_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((12, "throttled_at", "throttledAt"), string, ({||})) ) in
    fun t1 t2 -> {
    	id = (merge_id t1.id t2.id);
    	guid = (merge_guid t1.guid t2.guid);
    	delivered_at = (merge_delivered_at t1.delivered_at t2.delivered_at);
    	redelivery = (merge_redelivery t1.redelivery t2.redelivery);
    	duration = (merge_duration t1.duration t2.duration);
    	status = (merge_status t1.status t2.status);
    	status_code = (merge_status_code t1.status_code t2.status_code);
    	event = (merge_event t1.event t2.event);
    	action = (merge_action t1.action t2.action);
    	installation_id = (merge_installation_id t1.installation_id t2.installation_id);
    	repository_id = (merge_repository_id t1.repository_id t2.repository_id);
    	throttled_at = (merge_throttled_at t1.throttled_at t2.throttled_at);
     }
    let spec () = Runtime'.Spec.( basic ((1, "id", "id"), int64_int, (0)) ^:: basic ((2, "guid", "guid"), string, ({||})) ^:: basic ((3, "delivered_at", "deliveredAt"), string, ({||})) ^:: basic ((4, "redelivery", "redelivery"), bool, (false)) ^:: basic ((5, "duration", "duration"), double, (0.)) ^:: basic ((6, "status", "status"), string, ({||})) ^:: basic ((7, "status_code", "statusCode"), int64_int, (0)) ^:: basic ((8, "event", "event"), string, ({||})) ^:: basic ((9, "action", "action"), string, ({||})) ^:: basic ((10, "installation_id", "installationId"), int64_int, (0)) ^:: basic ((11, "repository_id", "repositoryId"), int64_int, (0)) ^:: basic ((12, "throttled_at", "throttledAt"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { id; guid; delivered_at; redelivery; duration; status; status_code; event; action; installation_id; repository_id; throttled_at } -> serialize writer id guid delivered_at redelivery duration status status_code event action installation_id repository_id throttled_at

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor id guid delivered_at redelivery duration status status_code event action installation_id repository_id throttled_at = { id; guid; delivered_at; redelivery; duration; status; status_code; event; action; installation_id; repository_id; throttled_at } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { id; guid; delivered_at; redelivery; duration; status; status_code; event; action; installation_id; repository_id; throttled_at } -> serialize id guid delivered_at redelivery duration status status_code event action installation_id repository_id throttled_at
    let from_json_exn =
      let constructor id guid delivered_at redelivery duration status status_code event action installation_id repository_id throttled_at = { id; guid; delivered_at; redelivery; duration; status; status_code; event; action; installation_id; repository_id; throttled_at } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

end

