(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: plugin/grpc/protocol/schedule.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot=''
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Protocol : sig

  (**
{%html:
<p>ScheduledJob represents a recurring Pulse schedule</p>
%}
  *)
  module rec ScheduledJob : sig
    type t = {
      id:string;
      ats_code:string;
      handler_name:string;
      payload:bytes;
      source_url:string;
      interval_seconds:int;
      next_run_at:string;
      (**
{%html:
<p>RFC3339 timestamp</p>
%}
      *)

      last_run_at:string;
      (**
{%html:
<p>RFC3339 timestamp (empty if never run)</p>
%}
      *)

      last_execution_id:string;
      state:string;
      (**
{%html:
<p>active, paused, deleted, inactive</p>
%}
      *)

      metadata:string;
      created_at:string;
      (**
{%html:
<p>RFC3339 timestamp</p>
%}
      *)

      updated_at:string;
      (**
{%html:
<p>RFC3339 timestamp</p>
%}
      *)

    }
    val make: ?id:string -> ?ats_code:string -> ?handler_name:string -> ?payload:bytes -> ?source_url:string -> ?interval_seconds:int -> ?next_run_at:string -> ?last_run_at:string -> ?last_execution_id:string -> ?state:string -> ?metadata:string -> ?created_at:string -> ?updated_at:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> ?ats_code:string -> ?handler_name:string -> ?payload:bytes -> ?source_url:string -> ?interval_seconds:int -> ?next_run_at:string -> ?last_run_at:string -> ?last_execution_id:string -> ?state:string -> ?metadata:string -> ?created_at:string -> ?updated_at:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and CreateScheduleRequest : sig
    type t = {
      auth_token:string;
      handler_name:string;
      (**
{%html:
<p>Handler to invoke on each tick</p>
%}
      *)

      interval_seconds:int;
      (**
{%html:
<p>Execution interval</p>
%}
      *)

      payload:bytes;
      (**
{%html:
<p>Handler-specific data (JSON)</p>
%}
      *)

      metadata:(string * string) list;
      (**
{%html:
<p>Optional metadata (glyph_id, plugin, etc.)</p>
%}
      *)

    }
    val make: ?auth_token:string -> ?handler_name:string -> ?interval_seconds:int -> ?payload:bytes -> ?metadata:(string * string) list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?handler_name:string -> ?interval_seconds:int -> ?payload:bytes -> ?metadata:(string * string) list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and CreateScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
      schedule_id:string;
      (**
{%html:
<p>The created schedule ID</p>
%}
      *)

    }
    val make: ?success:bool -> ?error:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and PauseScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and PauseScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and ResumeScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and ResumeScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and DeleteScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and DeleteScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GetScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  and GetScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
      job:ScheduledJob.t option;
    }
    val make: ?success:bool -> ?error:string -> ?job:ScheduledJob.t -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?job:ScheduledJob.t -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end

  module ScheduleService : sig
    module CreateSchedule : sig
      include Runtime'.Service.Rpc with type Request.t = CreateScheduleRequest.t and type Response.t = CreateScheduleResponse.t
      module Request : Runtime'.Spec.Message with type t = CreateScheduleRequest.t and type make_t = CreateScheduleRequest.make_t
      (** Module alias for the request message for this method call *)

      module Response : Runtime'.Spec.Message with type t = CreateScheduleResponse.t and type make_t = CreateScheduleResponse.make_t
      (** Module alias for the response message for this method call *)

    end

    val createSchedule : (module Runtime'.Spec.Message with type t = CreateScheduleRequest.t) * (module Runtime'.Spec.Message with type t = CreateScheduleResponse.t)
    module PauseSchedule : sig
      include Runtime'.Service.Rpc with type Request.t = PauseScheduleRequest.t and type Response.t = PauseScheduleResponse.t
      module Request : Runtime'.Spec.Message with type t = PauseScheduleRequest.t and type make_t = PauseScheduleRequest.make_t
      (** Module alias for the request message for this method call *)

      module Response : Runtime'.Spec.Message with type t = PauseScheduleResponse.t and type make_t = PauseScheduleResponse.make_t
      (** Module alias for the response message for this method call *)

    end

    val pauseSchedule : (module Runtime'.Spec.Message with type t = PauseScheduleRequest.t) * (module Runtime'.Spec.Message with type t = PauseScheduleResponse.t)
    module ResumeSchedule : sig
      include Runtime'.Service.Rpc with type Request.t = ResumeScheduleRequest.t and type Response.t = ResumeScheduleResponse.t
      module Request : Runtime'.Spec.Message with type t = ResumeScheduleRequest.t and type make_t = ResumeScheduleRequest.make_t
      (** Module alias for the request message for this method call *)

      module Response : Runtime'.Spec.Message with type t = ResumeScheduleResponse.t and type make_t = ResumeScheduleResponse.make_t
      (** Module alias for the response message for this method call *)

    end

    val resumeSchedule : (module Runtime'.Spec.Message with type t = ResumeScheduleRequest.t) * (module Runtime'.Spec.Message with type t = ResumeScheduleResponse.t)
    module DeleteSchedule : sig
      include Runtime'.Service.Rpc with type Request.t = DeleteScheduleRequest.t and type Response.t = DeleteScheduleResponse.t
      module Request : Runtime'.Spec.Message with type t = DeleteScheduleRequest.t and type make_t = DeleteScheduleRequest.make_t
      (** Module alias for the request message for this method call *)

      module Response : Runtime'.Spec.Message with type t = DeleteScheduleResponse.t and type make_t = DeleteScheduleResponse.make_t
      (** Module alias for the response message for this method call *)

    end

    val deleteSchedule : (module Runtime'.Spec.Message with type t = DeleteScheduleRequest.t) * (module Runtime'.Spec.Message with type t = DeleteScheduleResponse.t)
    module GetSchedule : sig
      include Runtime'.Service.Rpc with type Request.t = GetScheduleRequest.t and type Response.t = GetScheduleResponse.t
      module Request : Runtime'.Spec.Message with type t = GetScheduleRequest.t and type make_t = GetScheduleRequest.make_t
      (** Module alias for the request message for this method call *)

      module Response : Runtime'.Spec.Message with type t = GetScheduleResponse.t and type make_t = GetScheduleResponse.make_t
      (** Module alias for the response message for this method call *)

    end

    val getSchedule : (module Runtime'.Spec.Message with type t = GetScheduleRequest.t) * (module Runtime'.Spec.Message with type t = GetScheduleResponse.t)
  end

end = struct
  module rec ScheduledJob : sig
    type t = {
      id:string;
      ats_code:string;
      handler_name:string;
      payload:bytes;
      source_url:string;
      interval_seconds:int;
      next_run_at:string;
      (**
{%html:
<p>RFC3339 timestamp</p>
%}
      *)

      last_run_at:string;
      (**
{%html:
<p>RFC3339 timestamp (empty if never run)</p>
%}
      *)

      last_execution_id:string;
      state:string;
      (**
{%html:
<p>active, paused, deleted, inactive</p>
%}
      *)

      metadata:string;
      created_at:string;
      (**
{%html:
<p>RFC3339 timestamp</p>
%}
      *)

      updated_at:string;
      (**
{%html:
<p>RFC3339 timestamp</p>
%}
      *)

    }
    val make: ?id:string -> ?ats_code:string -> ?handler_name:string -> ?payload:bytes -> ?source_url:string -> ?interval_seconds:int -> ?next_run_at:string -> ?last_run_at:string -> ?last_execution_id:string -> ?state:string -> ?metadata:string -> ?created_at:string -> ?updated_at:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?id:string -> ?ats_code:string -> ?handler_name:string -> ?payload:bytes -> ?source_url:string -> ?interval_seconds:int -> ?next_run_at:string -> ?last_run_at:string -> ?last_execution_id:string -> ?state:string -> ?metadata:string -> ?created_at:string -> ?updated_at:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ScheduledJob
    let name () = ".protocol.ScheduledJob"
    type t = {
      id:string;
      ats_code:string;
      handler_name:string;
      payload:bytes;
      source_url:string;
      interval_seconds:int;
      next_run_at:string;
      last_run_at:string;
      last_execution_id:string;
      state:string;
      metadata:string;
      created_at:string;
      updated_at:string;
    }
    type make_t = ?id:string -> ?ats_code:string -> ?handler_name:string -> ?payload:bytes -> ?source_url:string -> ?interval_seconds:int -> ?next_run_at:string -> ?last_run_at:string -> ?last_execution_id:string -> ?state:string -> ?metadata:string -> ?created_at:string -> ?updated_at:string -> unit -> t
    let make ?(id = {||}) ?(ats_code = {||}) ?(handler_name = {||}) ?(payload = (Bytes.of_string {||})) ?(source_url = {||}) ?(interval_seconds = 0) ?(next_run_at = {||}) ?(last_run_at = {||}) ?(last_execution_id = {||}) ?(state = {||}) ?(metadata = {||}) ?(created_at = {||}) ?(updated_at = {||}) () = { id; ats_code; handler_name; payload; source_url; interval_seconds; next_run_at; last_run_at; last_execution_id; state; metadata; created_at; updated_at }
    let merge =
    let merge_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ) in
    let merge_ats_code = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "ats_code", "atsCode"), string, ({||})) ) in
    let merge_handler_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "handler_name", "handlerName"), string, ({||})) ) in
    let merge_payload = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "payload", "payload"), bytes, ((Bytes.of_string {||}))) ) in
    let merge_source_url = Runtime'.Merge.merge Runtime'.Spec.( basic ((5, "source_url", "sourceUrl"), string, ({||})) ) in
    let merge_interval_seconds = Runtime'.Merge.merge Runtime'.Spec.( basic ((6, "interval_seconds", "intervalSeconds"), int32_int, (0)) ) in
    let merge_next_run_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "next_run_at", "nextRunAt"), string, ({||})) ) in
    let merge_last_run_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((8, "last_run_at", "lastRunAt"), string, ({||})) ) in
    let merge_last_execution_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((9, "last_execution_id", "lastExecutionId"), string, ({||})) ) in
    let merge_state = Runtime'.Merge.merge Runtime'.Spec.( basic ((10, "state", "state"), string, ({||})) ) in
    let merge_metadata = Runtime'.Merge.merge Runtime'.Spec.( basic ((11, "metadata", "metadata"), string, ({||})) ) in
    let merge_created_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((12, "created_at", "createdAt"), string, ({||})) ) in
    let merge_updated_at = Runtime'.Merge.merge Runtime'.Spec.( basic ((13, "updated_at", "updatedAt"), string, ({||})) ) in
    fun t1 t2 -> {
    	id = (merge_id t1.id t2.id);
    	ats_code = (merge_ats_code t1.ats_code t2.ats_code);
    	handler_name = (merge_handler_name t1.handler_name t2.handler_name);
    	payload = (merge_payload t1.payload t2.payload);
    	source_url = (merge_source_url t1.source_url t2.source_url);
    	interval_seconds = (merge_interval_seconds t1.interval_seconds t2.interval_seconds);
    	next_run_at = (merge_next_run_at t1.next_run_at t2.next_run_at);
    	last_run_at = (merge_last_run_at t1.last_run_at t2.last_run_at);
    	last_execution_id = (merge_last_execution_id t1.last_execution_id t2.last_execution_id);
    	state = (merge_state t1.state t2.state);
    	metadata = (merge_metadata t1.metadata t2.metadata);
    	created_at = (merge_created_at t1.created_at t2.created_at);
    	updated_at = (merge_updated_at t1.updated_at t2.updated_at);
     }
    let spec () = Runtime'.Spec.( basic ((1, "id", "id"), string, ({||})) ^:: basic ((2, "ats_code", "atsCode"), string, ({||})) ^:: basic ((3, "handler_name", "handlerName"), string, ({||})) ^:: basic ((4, "payload", "payload"), bytes, ((Bytes.of_string {||}))) ^:: basic ((5, "source_url", "sourceUrl"), string, ({||})) ^:: basic ((6, "interval_seconds", "intervalSeconds"), int32_int, (0)) ^:: basic ((7, "next_run_at", "nextRunAt"), string, ({||})) ^:: basic ((8, "last_run_at", "lastRunAt"), string, ({||})) ^:: basic ((9, "last_execution_id", "lastExecutionId"), string, ({||})) ^:: basic ((10, "state", "state"), string, ({||})) ^:: basic ((11, "metadata", "metadata"), string, ({||})) ^:: basic ((12, "created_at", "createdAt"), string, ({||})) ^:: basic ((13, "updated_at", "updatedAt"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { id; ats_code; handler_name; payload; source_url; interval_seconds; next_run_at; last_run_at; last_execution_id; state; metadata; created_at; updated_at } -> serialize writer id ats_code handler_name payload source_url interval_seconds next_run_at last_run_at last_execution_id state metadata created_at updated_at

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor id ats_code handler_name payload source_url interval_seconds next_run_at last_run_at last_execution_id state metadata created_at updated_at = { id; ats_code; handler_name; payload; source_url; interval_seconds; next_run_at; last_run_at; last_execution_id; state; metadata; created_at; updated_at } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { id; ats_code; handler_name; payload; source_url; interval_seconds; next_run_at; last_run_at; last_execution_id; state; metadata; created_at; updated_at } -> serialize id ats_code handler_name payload source_url interval_seconds next_run_at last_run_at last_execution_id state metadata created_at updated_at
    let from_json_exn =
      let constructor id ats_code handler_name payload source_url interval_seconds next_run_at last_run_at last_execution_id state metadata created_at updated_at = { id; ats_code; handler_name; payload; source_url; interval_seconds; next_run_at; last_run_at; last_execution_id; state; metadata; created_at; updated_at } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and CreateScheduleRequest : sig
    type t = {
      auth_token:string;
      handler_name:string;
      (**
{%html:
<p>Handler to invoke on each tick</p>
%}
      *)

      interval_seconds:int;
      (**
{%html:
<p>Execution interval</p>
%}
      *)

      payload:bytes;
      (**
{%html:
<p>Handler-specific data (JSON)</p>
%}
      *)

      metadata:(string * string) list;
      (**
{%html:
<p>Optional metadata (glyph_id, plugin, etc.)</p>
%}
      *)

    }
    val make: ?auth_token:string -> ?handler_name:string -> ?interval_seconds:int -> ?payload:bytes -> ?metadata:(string * string) list -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?handler_name:string -> ?interval_seconds:int -> ?payload:bytes -> ?metadata:(string * string) list -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = CreateScheduleRequest
    let name () = ".protocol.CreateScheduleRequest"
    type t = {
      auth_token:string;
      handler_name:string;
      interval_seconds:int;
      payload:bytes;
      metadata:(string * string) list;
    }
    type make_t = ?auth_token:string -> ?handler_name:string -> ?interval_seconds:int -> ?payload:bytes -> ?metadata:(string * string) list -> unit -> t
    let make ?(auth_token = {||}) ?(handler_name = {||}) ?(interval_seconds = 0) ?(payload = (Bytes.of_string {||})) ?(metadata = []) () = { auth_token; handler_name; interval_seconds; payload; metadata }
    let merge =
    let merge_auth_token = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ) in
    let merge_handler_name = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "handler_name", "handlerName"), string, ({||})) ) in
    let merge_interval_seconds = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "interval_seconds", "intervalSeconds"), int32_int, (0)) ) in
    let merge_payload = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "payload", "payload"), bytes, ((Bytes.of_string {||}))) ) in
    let merge_metadata = Runtime'.Merge.merge Runtime'.Spec.( map ((5, "metadata", "metadata"), (string, basic ((2, "value", "value"), string, ({||})))) ) in
    fun t1 t2 -> {
    	auth_token = (merge_auth_token t1.auth_token t2.auth_token);
    	handler_name = (merge_handler_name t1.handler_name t2.handler_name);
    	interval_seconds = (merge_interval_seconds t1.interval_seconds t2.interval_seconds);
    	payload = (merge_payload t1.payload t2.payload);
    	metadata = (merge_metadata t1.metadata t2.metadata);
     }
    let spec () = Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ^:: basic ((2, "handler_name", "handlerName"), string, ({||})) ^:: basic ((3, "interval_seconds", "intervalSeconds"), int32_int, (0)) ^:: basic ((4, "payload", "payload"), bytes, ((Bytes.of_string {||}))) ^:: map ((5, "metadata", "metadata"), (string, basic ((2, "value", "value"), string, ({||})))) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { auth_token; handler_name; interval_seconds; payload; metadata } -> serialize writer auth_token handler_name interval_seconds payload metadata

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor auth_token handler_name interval_seconds payload metadata = { auth_token; handler_name; interval_seconds; payload; metadata } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { auth_token; handler_name; interval_seconds; payload; metadata } -> serialize auth_token handler_name interval_seconds payload metadata
    let from_json_exn =
      let constructor auth_token handler_name interval_seconds payload metadata = { auth_token; handler_name; interval_seconds; payload; metadata } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and CreateScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
      schedule_id:string;
      (**
{%html:
<p>The created schedule ID</p>
%}
      *)

    }
    val make: ?success:bool -> ?error:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = CreateScheduleResponse
    let name () = ".protocol.CreateScheduleResponse"
    type t = {
      success:bool;
      error:string;
      schedule_id:string;
    }
    type make_t = ?success:bool -> ?error:string -> ?schedule_id:string -> unit -> t
    let make ?(success = false) ?(error = {||}) ?(schedule_id = {||}) () = { success; error; schedule_id }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    let merge_schedule_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((3, "schedule_id", "scheduleId"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
    	schedule_id = (merge_schedule_id t1.schedule_id t2.schedule_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: basic ((3, "schedule_id", "scheduleId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error; schedule_id } -> serialize writer success error schedule_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error schedule_id = { success; error; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error; schedule_id } -> serialize success error schedule_id
    let from_json_exn =
      let constructor success error schedule_id = { success; error; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and PauseScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = PauseScheduleRequest
    let name () = ".protocol.PauseScheduleRequest"
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    let make ?(auth_token = {||}) ?(schedule_id = {||}) () = { auth_token; schedule_id }
    let merge =
    let merge_auth_token = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ) in
    let merge_schedule_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "schedule_id", "scheduleId"), string, ({||})) ) in
    fun t1 t2 -> {
    	auth_token = (merge_auth_token t1.auth_token t2.auth_token);
    	schedule_id = (merge_schedule_id t1.schedule_id t2.schedule_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ^:: basic ((2, "schedule_id", "scheduleId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { auth_token; schedule_id } -> serialize writer auth_token schedule_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { auth_token; schedule_id } -> serialize auth_token schedule_id
    let from_json_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and PauseScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = PauseScheduleResponse
    let name () = ".protocol.PauseScheduleResponse"
    type t = {
      success:bool;
      error:string;
    }
    type make_t = ?success:bool -> ?error:string -> unit -> t
    let make ?(success = false) ?(error = {||}) () = { success; error }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error } -> serialize writer success error

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error } -> serialize success error
    let from_json_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ResumeScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ResumeScheduleRequest
    let name () = ".protocol.ResumeScheduleRequest"
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    let make ?(auth_token = {||}) ?(schedule_id = {||}) () = { auth_token; schedule_id }
    let merge =
    let merge_auth_token = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ) in
    let merge_schedule_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "schedule_id", "scheduleId"), string, ({||})) ) in
    fun t1 t2 -> {
    	auth_token = (merge_auth_token t1.auth_token t2.auth_token);
    	schedule_id = (merge_schedule_id t1.schedule_id t2.schedule_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ^:: basic ((2, "schedule_id", "scheduleId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { auth_token; schedule_id } -> serialize writer auth_token schedule_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { auth_token; schedule_id } -> serialize auth_token schedule_id
    let from_json_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and ResumeScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = ResumeScheduleResponse
    let name () = ".protocol.ResumeScheduleResponse"
    type t = {
      success:bool;
      error:string;
    }
    type make_t = ?success:bool -> ?error:string -> unit -> t
    let make ?(success = false) ?(error = {||}) () = { success; error }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error } -> serialize writer success error

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error } -> serialize success error
    let from_json_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and DeleteScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = DeleteScheduleRequest
    let name () = ".protocol.DeleteScheduleRequest"
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    let make ?(auth_token = {||}) ?(schedule_id = {||}) () = { auth_token; schedule_id }
    let merge =
    let merge_auth_token = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ) in
    let merge_schedule_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "schedule_id", "scheduleId"), string, ({||})) ) in
    fun t1 t2 -> {
    	auth_token = (merge_auth_token t1.auth_token t2.auth_token);
    	schedule_id = (merge_schedule_id t1.schedule_id t2.schedule_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ^:: basic ((2, "schedule_id", "scheduleId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { auth_token; schedule_id } -> serialize writer auth_token schedule_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { auth_token; schedule_id } -> serialize auth_token schedule_id
    let from_json_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and DeleteScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
    }
    val make: ?success:bool -> ?error:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = DeleteScheduleResponse
    let name () = ".protocol.DeleteScheduleResponse"
    type t = {
      success:bool;
      error:string;
    }
    type make_t = ?success:bool -> ?error:string -> unit -> t
    let make ?(success = false) ?(error = {||}) () = { success; error }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error } -> serialize writer success error

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error } -> serialize success error
    let from_json_exn =
      let constructor success error = { success; error } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GetScheduleRequest : sig
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    val make: ?auth_token:string -> ?schedule_id:string -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GetScheduleRequest
    let name () = ".protocol.GetScheduleRequest"
    type t = {
      auth_token:string;
      schedule_id:string;
    }
    type make_t = ?auth_token:string -> ?schedule_id:string -> unit -> t
    let make ?(auth_token = {||}) ?(schedule_id = {||}) () = { auth_token; schedule_id }
    let merge =
    let merge_auth_token = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ) in
    let merge_schedule_id = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "schedule_id", "scheduleId"), string, ({||})) ) in
    fun t1 t2 -> {
    	auth_token = (merge_auth_token t1.auth_token t2.auth_token);
    	schedule_id = (merge_schedule_id t1.schedule_id t2.schedule_id);
     }
    let spec () = Runtime'.Spec.( basic ((1, "auth_token", "authToken"), string, ({||})) ^:: basic ((2, "schedule_id", "scheduleId"), string, ({||})) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { auth_token; schedule_id } -> serialize writer auth_token schedule_id

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { auth_token; schedule_id } -> serialize auth_token schedule_id
    let from_json_exn =
      let constructor auth_token schedule_id = { auth_token; schedule_id } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  and GetScheduleResponse : sig
    type t = {
      success:bool;
      error:string;
      job:ScheduledJob.t option;
    }
    val make: ?success:bool -> ?error:string -> ?job:ScheduledJob.t -> unit -> t
    (** Helper function to generate a message using default values *)

    val to_proto: t -> Runtime'.Writer.t
    (** Serialize the message to binary format *)

    val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from binary format *)

    val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
    (** Serialize to Json (compatible with Yojson.Basic.t) *)

    val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
    (** Deserialize from Json (compatible with Yojson.Basic.t) *)

    val name: unit -> string
    (** Fully qualified protobuf name of this message *)

    (**/**)
    type make_t = ?success:bool -> ?error:string -> ?job:ScheduledJob.t -> unit -> t
    val merge: t -> t -> t
    val to_proto': Runtime'.Writer.t -> t -> unit
    val from_proto_exn: Runtime'.Reader.t -> t
    val from_json_exn: Runtime'.Json.t -> t
    (**/**)
  end = struct
    module This'_ = GetScheduleResponse
    let name () = ".protocol.GetScheduleResponse"
    type t = {
      success:bool;
      error:string;
      job:ScheduledJob.t option;
    }
    type make_t = ?success:bool -> ?error:string -> ?job:ScheduledJob.t -> unit -> t
    let make ?(success = false) ?(error = {||}) ?job () = { success; error; job }
    let merge =
    let merge_success = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ) in
    let merge_error = Runtime'.Merge.merge Runtime'.Spec.( basic ((2, "error", "error"), string, ({||})) ) in
    let merge_job = Runtime'.Merge.merge Runtime'.Spec.( basic_opt ((3, "job", "job"), (message (module ScheduledJob))) ) in
    fun t1 t2 -> {
    	success = (merge_success t1.success t2.success);
    	error = (merge_error t1.error t2.error);
    	job = (merge_job t1.job t2.job);
     }
    let spec () = Runtime'.Spec.( basic ((1, "success", "success"), bool, (false)) ^:: basic ((2, "error", "error"), string, ({||})) ^:: basic_opt ((3, "job", "job"), (message (module ScheduledJob))) ^:: nil )
    let to_proto' =
      let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
      fun writer { success; error; job } -> serialize writer success error job

    let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
    let from_proto_exn =
      let constructor success error job = { success; error; job } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
    let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
    let to_json options =
      let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
      fun { success; error; job } -> serialize success error job
    let from_json_exn =
      let constructor success error job = { success; error; job } in
      Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
    let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
  end

  module ScheduleService = struct
    module CreateSchedule = struct
      let package_name = Some "protocol"
      let service_name = "ScheduleService"
      let method_name = "CreateSchedule"
      let name = "/protocol.ScheduleService/CreateSchedule"
      module Request = CreateScheduleRequest
      module Response = CreateScheduleResponse
    end

    let createSchedule =
      (module CreateScheduleRequest : Runtime'.Spec.Message with type t = CreateScheduleRequest.t ),
      (module CreateScheduleResponse : Runtime'.Spec.Message with type t = CreateScheduleResponse.t )

    module PauseSchedule = struct
      let package_name = Some "protocol"
      let service_name = "ScheduleService"
      let method_name = "PauseSchedule"
      let name = "/protocol.ScheduleService/PauseSchedule"
      module Request = PauseScheduleRequest
      module Response = PauseScheduleResponse
    end

    let pauseSchedule =
      (module PauseScheduleRequest : Runtime'.Spec.Message with type t = PauseScheduleRequest.t ),
      (module PauseScheduleResponse : Runtime'.Spec.Message with type t = PauseScheduleResponse.t )

    module ResumeSchedule = struct
      let package_name = Some "protocol"
      let service_name = "ScheduleService"
      let method_name = "ResumeSchedule"
      let name = "/protocol.ScheduleService/ResumeSchedule"
      module Request = ResumeScheduleRequest
      module Response = ResumeScheduleResponse
    end

    let resumeSchedule =
      (module ResumeScheduleRequest : Runtime'.Spec.Message with type t = ResumeScheduleRequest.t ),
      (module ResumeScheduleResponse : Runtime'.Spec.Message with type t = ResumeScheduleResponse.t )

    module DeleteSchedule = struct
      let package_name = Some "protocol"
      let service_name = "ScheduleService"
      let method_name = "DeleteSchedule"
      let name = "/protocol.ScheduleService/DeleteSchedule"
      module Request = DeleteScheduleRequest
      module Response = DeleteScheduleResponse
    end

    let deleteSchedule =
      (module DeleteScheduleRequest : Runtime'.Spec.Message with type t = DeleteScheduleRequest.t ),
      (module DeleteScheduleResponse : Runtime'.Spec.Message with type t = DeleteScheduleResponse.t )

    module GetSchedule = struct
      let package_name = Some "protocol"
      let service_name = "ScheduleService"
      let method_name = "GetSchedule"
      let name = "/protocol.ScheduleService/GetSchedule"
      module Request = GetScheduleRequest
      module Response = GetScheduleResponse
    end

    let getSchedule =
      (module GetScheduleRequest : Runtime'.Spec.Message with type t = GetScheduleRequest.t ),
      (module GetScheduleResponse : Runtime'.Spec.Message with type t = GetScheduleResponse.t )

  end

end

