/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const classify_claims: (a: number, b: number) => [number, number];
export const cosine_similarity_f32: (a: number, b: number, c: number, d: number) => [number, number, number];
export const delete_attestation: (a: number, b: number) => any;
export const exists_attestation: (a: number, b: number) => any;
export const generate_asuid: (a: number, b: number) => [number, number];
export const get_attestation: (a: number, b: number) => any;
export const id_clean_seed: (a: number, b: number) => [number, number];
export const id_normalize_for_lookup: (a: number, b: number) => [number, number];
export const init_store: (a: number, b: number) => any;
export const is_store_initialized: () => number;
export const list_attestation_ids: () => any;
export const parse_query: (a: number, b: number) => [number, number];
export const put_attestation: (a: number, b: number) => any;
export const query_attestations: (a: number, b: number) => any;
export const version: () => [number, number];
export const wasm_bindgen__closure__destroy__h0b10cf666a0fcdb7: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h078189f2bfbdcfe4: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7360c8efb9a95e5b: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h10d39837d52e97df: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h331fab369fed6b82: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
