/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const classify_claims: (a: number, b: number) => [number, number];
export const delete_attestation: (a: number, b: number) => any;
export const exists_attestation: (a: number, b: number) => any;
export const fuzzy_rebuild_index: () => any;
export const fuzzy_search: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const fuzzy_status: () => [number, number];
export const get_attestation: (a: number, b: number) => any;
export const init_store: (a: number, b: number) => any;
export const is_store_initialized: () => number;
export const list_attestation_ids: () => any;
export const parse_query: (a: number, b: number) => [number, number];
export const put_attestation: (a: number, b: number) => any;
export const query_attestations: (a: number, b: number) => any;
export const version: () => [number, number];
export const wasm_bindgen__closure__destroy__h9e9eb2a865ed478c: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h8220019b907fc76c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hbd107e223a93ecf5: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h38672a799bd6a05d: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb0bc71d46e4311a7: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
