// Code generated by typegen from Go source. DO NOT EDIT.
// Regenerate with: make types
// TODO: Migrate to proto generation
// Source package: schedule
// Source last modified: 2026-08-06T19:27:50+02:00
// Source version: 91411476

//! # schedule module
//!
//! Generated from Go package: schedule
//!
//! This module contains auto-generated type definitions.
//! All types include serde Serialize/Deserialize traits for JSON compatibility.

#![allow(clippy::all)]
#![allow(unused_imports)]

pub const EXECUTION_STATUS_COMPLETED: &str = "completed";
pub const EXECUTION_STATUS_FAILED: &str = "failed";
pub const EXECUTION_STATUS_RUNNING: &str = "running";
pub const STATE_ACTIVE: &str = "active";
pub const STATE_DELETED: &str = "deleted";
pub const STATE_INACTIVE: &str = "inactive";
pub const STATE_PAUSED: &str = "paused";
pub const STATE_STOPPING: &str = "stopping";

/// TaskLogStore handles persistence of task-level execution logs.
/// The task_logs table captures per-stage, per-task log output from async job executions.
#[doc = "Documentation: <https://github.com/teranos/QNTX/blob/main/docs/types/schedule.md#tasklogstore>"]
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TaskLogStore {}
