(* DomainPluginService implementation for qntx-loom
 *
 * Implements the gRPC contract from domain.proto using ocaml-protoc-plugin
 * generated types and grpc-lwt for the HTTP/2 server.
 *
 * Architecture note: grpc-lwt sits on top of h2 (an HTTP/2 implementation)
 * rather than using Google's C-based gRPC core. This is the pure-OCaml path —
 * no C FFI, no libgrpc dependency. The trade-off is that this ecosystem is
 * younger and less battle-tested than grpc-go or grpc-java, but it compiles
 * to a single native binary with no runtime dependencies.
 *
 * The flow for each unary RPC:
 * 1. h2 receives an HTTP/2 request with content-type: application/grpc
 * 2. grpc-lwt extracts the length-prefixed protobuf message from the body
 * 3. We deserialize using Protocol.*.from_proto (generated by ocaml-protoc-plugin)
 * 4. We run our handler logic and build a response type
 * 5. We serialize with Protocol.*.to_proto, which returns a Writer.t
 * 6. Writer.contents extracts the serialized bytes as a string
 * 7. grpc-lwt wraps it back in the gRPC framing and sends it as HTTP/2 response
 *)

open Qntx_loom_proto.Domain

let name = "loom"
let version = Version.value

(* State set during Initialize *)
let ats_endpoint = ref ""

(* --- Serialization helpers --- *)

(* ocaml-protoc-plugin's to_proto returns a Writer.t — a buffer builder.
 * Writer.contents extracts the final bytes. This two-step design lets the
 * library avoid intermediate allocations when building nested messages. *)
let proto_to_string writer =
  Ocaml_protoc_plugin.Writer.contents writer

(* --- RPC Handlers --- *)

(* Each handler is a grpc-lwt "unary" function:
 *   string -> (Grpc.Status.t * string option) Lwt.t
 *
 * The input string is raw protobuf bytes (already extracted from gRPC framing).
 * The output is a gRPC status + optional response bytes.
 * Lwt.t is the async monad — like a Promise in JS or a Future in Rust. *)

let handle_metadata _raw =
  let resp = Protocol.MetadataResponse.make
    ~name
    ~version
    ~description:"Commit-scoped transcript stitcher"
    () in
  let encoded = proto_to_string (Protocol.MetadataResponse.to_proto resp) in
  Lwt.return (Grpc.Status.(v OK), Some encoded)

let handle_health _raw =
  let resp = Protocol.HealthResponse.make
    ~healthy:true
    ~message:"ok"
    () in
  let encoded = proto_to_string (Protocol.HealthResponse.to_proto resp) in
  Lwt.return (Grpc.Status.(v OK), Some encoded)

let handle_initialize raw =
  (* Decode the InitializeRequest to extract service endpoints.
   * from_proto takes a Reader.t and returns a result type:
   * Ok v — decoded successfully, or Error _ — malformed protobuf. *)
  let reader = Ocaml_protoc_plugin.Reader.create raw in
  (match Protocol.InitializeRequest.from_proto reader with
   | Ok req ->
     ats_endpoint := req.ats_store_endpoint;
     Printf.printf "[loom] Initialized with ATS endpoint: %s\n%!" req.ats_store_endpoint;
     (* Configure the ATS client so it can create weave attestations *)
     Ats_client.configure
       ~ats_endpoint:req.ats_store_endpoint
       ~token:req.auth_token
   | Error _ ->
     Printf.printf "[loom] Warning: could not decode InitializeRequest\n%!");
  let resp = Protocol.InitializeResponse.make
    ~handler_names:["stitch"]
    () in
  let encoded = proto_to_string (Protocol.InitializeResponse.to_proto resp) in
  Lwt.return (Grpc.Status.(v OK), Some encoded)

let handle_execute_job raw =
  let open Lwt.Syntax in
  let reader = Ocaml_protoc_plugin.Reader.create raw in
  match Protocol.ExecuteJobRequest.from_proto reader with
  | Ok req ->
    Printf.printf "[loom] ExecuteJob handler=%s job_id=%s (%d bytes payload)\n%!"
      req.handler_name req.job_id (Bytes.length req.payload);
    let payload_str = Bytes.to_string req.payload in
    (match req.handler_name with
     | "stitch" ->
       let results = Stitcher.stitch payload_str in
       (* If the stitcher emitted weave(s), persist via ATSStoreService.
        * Lwt.async fires the RPC without blocking the ExecuteJob response —
        * we don't want QNTX waiting on the ATS round-trip. *)
       List.iter (fun (result : Stitcher.stitch_result) ->
         match result.emitted with
         | Some block ->
           Lwt.async (fun () ->
             let* ats_result = Ats_client.create_weave
               ~branch:result.branch
               ~context:result.context
               ~text:block
               ~word_count:(Stitcher.word_count block)
               ~turn_count:result.turn_count
             in
             (match ats_result with
              | Ok () -> ()
              | Error msg ->
                Printf.eprintf "[loom] Failed to persist weave: %s\n%!" msg);
             Lwt.return_unit)
         | None -> ()
       ) results;
       (* Return the last result for the ExecuteJob response *)
       let result = List.nth results (List.length results - 1) in
       let result_json = Stitcher.result_to_json result in
       let resp = Protocol.ExecuteJobResponse.make
         ~success:true
         ~result:(Bytes.of_string result_json)
         ~plugin_version:version
         () in
       let encoded = proto_to_string (Protocol.ExecuteJobResponse.to_proto resp) in
       Lwt.return (Grpc.Status.(v OK), Some encoded)
     | other ->
       let resp = Protocol.ExecuteJobResponse.make
         ~success:false
         ~error:(Printf.sprintf "unknown handler: %s" other)
         ~plugin_version:version
         () in
       let encoded = proto_to_string (Protocol.ExecuteJobResponse.to_proto resp) in
       Lwt.return (Grpc.Status.(v OK), Some encoded))
  | Error e ->
    let msg = Ocaml_protoc_plugin.Result.show_error e in
    let resp = Protocol.ExecuteJobResponse.make
      ~success:false
      ~error:(Printf.sprintf "failed to decode ExecuteJobRequest: %s" msg)
      ~plugin_version:version
      () in
    let encoded = proto_to_string (Protocol.ExecuteJobResponse.to_proto resp) in
    Lwt.return (Grpc.Status.(v OK), Some encoded)

let handle_config_schema _raw =
  let resp = Protocol.ConfigSchemaResponse.make () in
  let encoded = proto_to_string (Protocol.ConfigSchemaResponse.to_proto resp) in
  Lwt.return (Grpc.Status.(v OK), Some encoded)

let flush_and_persist () =
  let open Lwt.Syntax in
  let flushed = Stitcher.flush_all () in
  let* () = Lwt_list.iter_p (fun (result : Stitcher.stitch_result) ->
    match result.emitted with
    | Some block ->
      let* ats_result = Ats_client.create_weave
        ~branch:result.branch
        ~context:result.context
        ~text:block
        ~word_count:(Stitcher.word_count block)
        ~turn_count:result.turn_count
      in
      (match ats_result with
       | Ok () -> ()
       | Error msg ->
         Printf.eprintf "[loom] Failed to persist flushed weave for %s: %s\n%!" result.branch msg);
      Lwt.return_unit
    | None -> Lwt.return_unit
  ) flushed in
  Printf.printf "[loom] Flushed %d weave(s)\n%!" (List.length flushed);
  Lwt.return_unit

let handle_shutdown _raw =
  let open Lwt.Syntax in
  Printf.printf "[loom] Shutting down — flushing buffered weaves\n%!";
  let* () = flush_and_persist () in
  let encoded = proto_to_string (Protocol.Empty.to_proto (Protocol.Empty.make ())) in
  Lwt.return (Grpc.Status.(v OK), Some encoded)

(* --- gRPC service wiring --- *)

(* grpc-lwt uses a builder pattern: create a Service, add RPCs by name,
 * then wrap the service in a Server keyed by the fully-qualified proto
 * service name. The RPC names must match the method names from the proto
 * definition — "Metadata", "Initialize", etc. — because gRPC routes by
 * the HTTP/2 :path pseudo-header which is "/package.Service/Method". *)

let build_service () =
  Grpc_lwt.Server.Service.(
    v ()
    |> add_rpc ~name:"Metadata" ~rpc:(Unary handle_metadata)
    |> add_rpc ~name:"Initialize" ~rpc:(Unary handle_initialize)
    |> add_rpc ~name:"Health" ~rpc:(Unary handle_health)
    |> add_rpc ~name:"ExecuteJob" ~rpc:(Unary handle_execute_job)
    |> add_rpc ~name:"ConfigSchema" ~rpc:(Unary handle_config_schema)
    |> add_rpc ~name:"Shutdown" ~rpc:(Unary handle_shutdown)
  )

(* --- Custom request handler --- *)

(* grpc-lwt's built-in Server.handle_request demands that "identity" appear
 * in the grpc-accept-encoding header. But per the gRPC spec (compression.md),
 * "identity" is always implicitly accepted unless explicitly rejected — clients
 * are not required to list it. grpc-go only sends registered compressors
 * (e.g. "gzip"), which is spec-compliant. grpc-lwt's check is a bug.
 *
 * We bypass grpc-lwt's top-level router and only validate content-type,
 * while still using grpc-lwt's Service.handle_request for RPC dispatch. *)

let service = lazy (build_service ())

let route_request reqd =
  let request = H2.Reqd.request reqd in
  let respond_with code =
    H2.Reqd.respond_with_string reqd (H2.Response.create code) ""
  in
  match request.meth with
  | `POST ->
    (match H2.Headers.get request.headers "content-type" with
     | Some s when String.length s >= 16 && String.sub s 0 16 = "application/grpc" ->
       (* Route to the service — ignore encoding negotiation *)
       Grpc_lwt.Server.Service.handle_request (Lazy.force service) reqd
     | _ ->
       respond_with `Unsupported_media_type)
  | _ ->
    respond_with `Not_found

(* --- HTTP/2 server --- *)

(* QNTX talks to plugins over h2c (HTTP/2 cleartext — no TLS) on localhost.
 * There's no need for TLS when both processes are on the same machine and
 * communicate over loopback. The H2_lwt_unix module gives us a connection
 * handler that we feed to Lwt's TCP server.
 *
 * The error_handler is required by h2 — it fires for protocol-level errors
 * like malformed HTTP/2 frames, not application-level gRPC errors. *)

let serve port =
  let request_handler _addr reqd =
    route_request reqd
  in
  let error_handler _addr ?request:_ error respond =
    let msg = match error with
      | `Exn exn -> Printexc.to_string exn
      | `Bad_gateway -> "Bad gateway"
      | `Bad_request -> "Bad request"
      | `Internal_server_error -> "Internal server error"
    in
    Printf.eprintf "[loom] HTTP/2 error: %s\n%!" msg;
    let body = respond H2.Headers.empty in
    H2.Body.Writer.close body
  in
  let connection_handler =
    H2_lwt_unix.Server.create_connection_handler
      ~request_handler
      ~error_handler
  in
  (* Port auto-increment: if the requested port is taken (stale process,
   * another QNTX instance), try up to 10 consecutive ports. This matches
   * the behavior of Go plugins. The actual port is announced to QNTX via
   * QNTX_PLUGIN_PORT= on stdout AFTER successful bind. *)
  let max_attempts = 10 in
  let open Lwt.Syntax in
  let rec try_bind attempt current_port =
    if attempt >= max_attempts then
      Lwt.fail_with (Printf.sprintf "failed to bind after %d attempts (ports %d-%d)"
        max_attempts port (port + max_attempts - 1))
    else
      let listen_addr = Unix.(ADDR_INET (inet_addr_loopback, current_port)) in
      Lwt.catch
        (fun () ->
          let* _server =
            Lwt_io.establish_server_with_client_socket listen_addr connection_handler
          in
          Lwt.return current_port)
        (fun _exn ->
          Printf.eprintf "[loom] Port %d in use, trying %d\n%!" current_port (current_port + 1);
          try_bind (attempt + 1) (current_port + 1))
  in
  let* actual_port = try_bind 0 port in
  (* Announce actual port — QNTX reads this line to know where to connect *)
  Printf.printf "QNTX_PLUGIN_PORT=%d\n%!" actual_port;
  Printf.printf "[loom] gRPC server listening on port %d\n%!" actual_port;
  (* Start UDP listener alongside the gRPC server *)
  Lwt.async (fun () ->
    Lwt.catch
      (fun () -> Udp_listener.start ())
      (fun exn ->
        Printf.eprintf "[loom] UDP listener failed: %s\n%!" (Printexc.to_string exn);
        Lwt.return_unit));
  (* Block forever — QNTX manages our lifecycle via the Shutdown RPC *)
  let forever, _ = Lwt.wait () in
  forever
