// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: plugin/grpc/protocol/domain.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DomainPluginService_Metadata_FullMethodName        = "/protocol.DomainPluginService/Metadata"
	DomainPluginService_Initialize_FullMethodName      = "/protocol.DomainPluginService/Initialize"
	DomainPluginService_Shutdown_FullMethodName        = "/protocol.DomainPluginService/Shutdown"
	DomainPluginService_HandleHTTP_FullMethodName      = "/protocol.DomainPluginService/HandleHTTP"
	DomainPluginService_HandleWebSocket_FullMethodName = "/protocol.DomainPluginService/HandleWebSocket"
	DomainPluginService_Health_FullMethodName          = "/protocol.DomainPluginService/Health"
	DomainPluginService_ConfigSchema_FullMethodName    = "/protocol.DomainPluginService/ConfigSchema"
	DomainPluginService_ExecuteJob_FullMethodName      = "/protocol.DomainPluginService/ExecuteJob"
)

// DomainPluginServiceClient is the client API for DomainPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DomainPluginService is the gRPC service for external domain plugins
type DomainPluginServiceClient interface {
	// Metadata returns plugin metadata
	Metadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetadataResponse, error)
	// Initialize initializes the plugin
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// Shutdown shuts down the plugin
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// HandleHTTP handles an HTTP request
	HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
	// HandleWebSocket handles a WebSocket connection (bidirectional streaming)
	HandleWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketMessage, WebSocketMessage], error)
	// Health checks plugin health
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// ConfigSchema returns the configuration schema for this plugin
	ConfigSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigSchemaResponse, error)
	// ExecuteJob executes an async job
	// Used by Pulse to route jobs to plugin-registered handlers
	ExecuteJob(ctx context.Context, in *ExecuteJobRequest, opts ...grpc.CallOption) (*ExecuteJobResponse, error)
}

type domainPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainPluginServiceClient(cc grpc.ClientConnInterface) DomainPluginServiceClient {
	return &domainPluginServiceClient{cc}
}

func (c *domainPluginServiceClient) Metadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, DomainPluginService_Metadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainPluginServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, DomainPluginService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainPluginServiceClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DomainPluginService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainPluginServiceClient) HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, DomainPluginService_HandleHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainPluginServiceClient) HandleWebSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WebSocketMessage, WebSocketMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DomainPluginService_ServiceDesc.Streams[0], DomainPluginService_HandleWebSocket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WebSocketMessage, WebSocketMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DomainPluginService_HandleWebSocketClient = grpc.BidiStreamingClient[WebSocketMessage, WebSocketMessage]

func (c *domainPluginServiceClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DomainPluginService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainPluginServiceClient) ConfigSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSchemaResponse)
	err := c.cc.Invoke(ctx, DomainPluginService_ConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainPluginServiceClient) ExecuteJob(ctx context.Context, in *ExecuteJobRequest, opts ...grpc.CallOption) (*ExecuteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteJobResponse)
	err := c.cc.Invoke(ctx, DomainPluginService_ExecuteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainPluginServiceServer is the server API for DomainPluginService service.
// All implementations must embed UnimplementedDomainPluginServiceServer
// for forward compatibility.
//
// DomainPluginService is the gRPC service for external domain plugins
type DomainPluginServiceServer interface {
	// Metadata returns plugin metadata
	Metadata(context.Context, *Empty) (*MetadataResponse, error)
	// Initialize initializes the plugin
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// Shutdown shuts down the plugin
	Shutdown(context.Context, *Empty) (*Empty, error)
	// HandleHTTP handles an HTTP request
	HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error)
	// HandleWebSocket handles a WebSocket connection (bidirectional streaming)
	HandleWebSocket(grpc.BidiStreamingServer[WebSocketMessage, WebSocketMessage]) error
	// Health checks plugin health
	Health(context.Context, *Empty) (*HealthResponse, error)
	// ConfigSchema returns the configuration schema for this plugin
	ConfigSchema(context.Context, *Empty) (*ConfigSchemaResponse, error)
	// ExecuteJob executes an async job
	// Used by Pulse to route jobs to plugin-registered handlers
	ExecuteJob(context.Context, *ExecuteJobRequest) (*ExecuteJobResponse, error)
	mustEmbedUnimplementedDomainPluginServiceServer()
}

// UnimplementedDomainPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDomainPluginServiceServer struct{}

func (UnimplementedDomainPluginServiceServer) Metadata(context.Context, *Empty) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Metadata not implemented")
}
func (UnimplementedDomainPluginServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedDomainPluginServiceServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDomainPluginServiceServer) HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTP not implemented")
}
func (UnimplementedDomainPluginServiceServer) HandleWebSocket(grpc.BidiStreamingServer[WebSocketMessage, WebSocketMessage]) error {
	return status.Error(codes.Unimplemented, "method HandleWebSocket not implemented")
}
func (UnimplementedDomainPluginServiceServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDomainPluginServiceServer) ConfigSchema(context.Context, *Empty) (*ConfigSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigSchema not implemented")
}
func (UnimplementedDomainPluginServiceServer) ExecuteJob(context.Context, *ExecuteJobRequest) (*ExecuteJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteJob not implemented")
}
func (UnimplementedDomainPluginServiceServer) mustEmbedUnimplementedDomainPluginServiceServer() {}
func (UnimplementedDomainPluginServiceServer) testEmbeddedByValue()                             {}

// UnsafeDomainPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainPluginServiceServer will
// result in compilation errors.
type UnsafeDomainPluginServiceServer interface {
	mustEmbedUnimplementedDomainPluginServiceServer()
}

func RegisterDomainPluginServiceServer(s grpc.ServiceRegistrar, srv DomainPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedDomainPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DomainPluginService_ServiceDesc, srv)
}

func _DomainPluginService_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainPluginServiceServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainPluginService_Metadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainPluginServiceServer).Metadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainPluginService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainPluginServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainPluginService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainPluginServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainPluginService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainPluginServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainPluginService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainPluginServiceServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainPluginService_HandleHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainPluginServiceServer).HandleHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainPluginService_HandleHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainPluginServiceServer).HandleHTTP(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainPluginService_HandleWebSocket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DomainPluginServiceServer).HandleWebSocket(&grpc.GenericServerStream[WebSocketMessage, WebSocketMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DomainPluginService_HandleWebSocketServer = grpc.BidiStreamingServer[WebSocketMessage, WebSocketMessage]

func _DomainPluginService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainPluginServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainPluginService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainPluginServiceServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainPluginService_ConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainPluginServiceServer).ConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainPluginService_ConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainPluginServiceServer).ConfigSchema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainPluginService_ExecuteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainPluginServiceServer).ExecuteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainPluginService_ExecuteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainPluginServiceServer).ExecuteJob(ctx, req.(*ExecuteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainPluginService_ServiceDesc is the grpc.ServiceDesc for DomainPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.DomainPluginService",
	HandlerType: (*DomainPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Metadata",
			Handler:    _DomainPluginService_Metadata_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _DomainPluginService_Initialize_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DomainPluginService_Shutdown_Handler,
		},
		{
			MethodName: "HandleHTTP",
			Handler:    _DomainPluginService_HandleHTTP_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DomainPluginService_Health_Handler,
		},
		{
			MethodName: "ConfigSchema",
			Handler:    _DomainPluginService_ConfigSchema_Handler,
		},
		{
			MethodName: "ExecuteJob",
			Handler:    _DomainPluginService_ExecuteJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HandleWebSocket",
			Handler:       _DomainPluginService_HandleWebSocket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin/grpc/protocol/domain.proto",
}
