// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: plugin/grpc/protocol/fetch.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`             // URL to fetch
	Subjects      []string               `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`   // Attestation subjects
	Predicate     string                 `protobuf:"bytes,4,opt,name=predicate,proto3" json:"predicate,omitempty"` // Attestation predicate (e.g. "http:get")
	Context       string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`     // Attestation context (e.g. the URL itself)
	Fresh         bool                   `protobuf:"varint,6,opt,name=fresh,proto3" json:"fresh,omitempty"`        // Skip cache, always fetch from remote
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_plugin_grpc_protocol_fetch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_fetch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_fetch_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *FetchRequest) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *FetchRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *FetchRequest) GetFresh() bool {
	if x != nil {
		return x.Fresh
	}
	return false
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                                        // Response body
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`         // HTTP status code
	AttestationId string                 `protobuf:"bytes,5,opt,name=attestation_id,json=attestationId,proto3" json:"attestation_id,omitempty"` // ID of created attestation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_plugin_grpc_protocol_fetch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_fetch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_fetch_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FetchResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FetchResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FetchResponse) GetAttestationId() string {
	if x != nil {
		return x.AttestationId
	}
	return ""
}

var File_plugin_grpc_protocol_fetch_proto protoreflect.FileDescriptor

const file_plugin_grpc_protocol_fetch_proto_rawDesc = "" +
	"\n" +
	" plugin/grpc/protocol/fetch.proto\x12\bprotocol\"\xa9\x01\n" +
	"\fFetchRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bsubjects\x18\x03 \x03(\tR\bsubjects\x12\x1c\n" +
	"\tpredicate\x18\x04 \x01(\tR\tpredicate\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x12\x14\n" +
	"\x05fresh\x18\x06 \x01(\bR\x05fresh\"\x9b\x01\n" +
	"\rFetchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0eattestation_id\x18\x05 \x01(\tR\rattestationId2H\n" +
	"\fFetchService\x128\n" +
	"\x05Fetch\x12\x16.protocol.FetchRequest\x1a\x17.protocol.FetchResponseB.Z,github.com/teranos/QNTX/plugin/grpc/protocolb\x06proto3"

var (
	file_plugin_grpc_protocol_fetch_proto_rawDescOnce sync.Once
	file_plugin_grpc_protocol_fetch_proto_rawDescData []byte
)

func file_plugin_grpc_protocol_fetch_proto_rawDescGZIP() []byte {
	file_plugin_grpc_protocol_fetch_proto_rawDescOnce.Do(func() {
		file_plugin_grpc_protocol_fetch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_fetch_proto_rawDesc), len(file_plugin_grpc_protocol_fetch_proto_rawDesc)))
	})
	return file_plugin_grpc_protocol_fetch_proto_rawDescData
}

var file_plugin_grpc_protocol_fetch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_grpc_protocol_fetch_proto_goTypes = []any{
	(*FetchRequest)(nil),  // 0: protocol.FetchRequest
	(*FetchResponse)(nil), // 1: protocol.FetchResponse
}
var file_plugin_grpc_protocol_fetch_proto_depIdxs = []int32{
	0, // 0: protocol.FetchService.Fetch:input_type -> protocol.FetchRequest
	1, // 1: protocol.FetchService.Fetch:output_type -> protocol.FetchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_grpc_protocol_fetch_proto_init() }
func file_plugin_grpc_protocol_fetch_proto_init() {
	if File_plugin_grpc_protocol_fetch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_fetch_proto_rawDesc), len(file_plugin_grpc_protocol_fetch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_grpc_protocol_fetch_proto_goTypes,
		DependencyIndexes: file_plugin_grpc_protocol_fetch_proto_depIdxs,
		MessageInfos:      file_plugin_grpc_protocol_fetch_proto_msgTypes,
	}.Build()
	File_plugin_grpc_protocol_fetch_proto = out.File
	file_plugin_grpc_protocol_fetch_proto_goTypes = nil
	file_plugin_grpc_protocol_fetch_proto_depIdxs = nil
}
