syntax = "proto3";

package protocol;

import "google/protobuf/struct.proto";

option go_package = "github.com/teranos/QNTX/plugin/grpc/protocol";

// ADR-043
// https://docs.github.com/en/rest/repos/repos?apiVersion=2026-03-10

message GitHubReposReposListOrganizationRepositoriesRequest {
  string namespace = 1;
}

message GitHubReposReposListOrganizationRepositoriesResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubReposReposMinimalRepository items = 3;
}

message GitHubReposReposCreateAnOrganizationRepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposCreateAnOrganizationRepositoryResponse {
  message Permissions {
    bool admin = 1;
    bool maintain = 2;
    bool push = 3;
    bool triage = 4;
    bool pull = 5;
  }
  message SecurityAndAnalysis {
    message AdvancedSecurity {
      string status = 1;
    }
    message CodeSecurity {
      string status = 1;
    }
    message DependabotSecurityUpdates {
      string status = 1;
    }
    message SecretScanning {
      string status = 1;
    }
    message SecretScanningPushProtection {
      string status = 1;
    }
    message SecretScanningNonProviderPatterns {
      string status = 1;
    }
    message SecretScanningAiDetection {
      string status = 1;
    }
    message SecretScanningDelegatedAlertDismissal {
      string status = 1;
    }
    message SecretScanningDelegatedBypass {
      string status = 1;
    }
    message SecretScanningDelegatedBypassOptions {
      message Reviewers {
        int64 reviewer_id = 1;
        string reviewer_type = 2;
        string mode = 3;
      }
      repeated Reviewers reviewers = 1;
    }
    AdvancedSecurity advanced_security = 1;
    CodeSecurity code_security = 2;
    DependabotSecurityUpdates dependabot_security_updates = 3;
    SecretScanning secret_scanning = 4;
    SecretScanningPushProtection secret_scanning_push_protection = 5;
    SecretScanningNonProviderPatterns secret_scanning_non_provider_patterns = 6;
    SecretScanningAiDetection secret_scanning_ai_detection = 7;
    SecretScanningDelegatedAlertDismissal secret_scanning_delegated_alert_dismissal = 8;
    SecretScanningDelegatedBypass secret_scanning_delegated_bypass = 9;
    SecretScanningDelegatedBypassOptions secret_scanning_delegated_bypass_options = 10;
  }
  bool success = 1;
  string error = 2;
  int64 id = 3;
  string node_id = 4;
  string name = 5;
  string full_name = 6;
  GitHubReposReposSimpleUser owner = 7;
  bool private = 8;
  string html_url = 9;
  string description = 10;
  bool fork = 11;
  string url = 12;
  string archive_url = 13;
  string assignees_url = 14;
  string blobs_url = 15;
  string branches_url = 16;
  string collaborators_url = 17;
  string comments_url = 18;
  string commits_url = 19;
  string compare_url = 20;
  string contents_url = 21;
  string contributors_url = 22;
  string deployments_url = 23;
  string downloads_url = 24;
  string events_url = 25;
  string forks_url = 26;
  string git_commits_url = 27;
  string git_refs_url = 28;
  string git_tags_url = 29;
  string git_url = 30;
  string issue_comment_url = 31;
  string issue_events_url = 32;
  string issues_url = 33;
  string keys_url = 34;
  string labels_url = 35;
  string languages_url = 36;
  string merges_url = 37;
  string milestones_url = 38;
  string notifications_url = 39;
  string pulls_url = 40;
  string releases_url = 41;
  string ssh_url = 42;
  string stargazers_url = 43;
  string statuses_url = 44;
  string subscribers_url = 45;
  string subscription_url = 46;
  string tags_url = 47;
  string teams_url = 48;
  string trees_url = 49;
  string clone_url = 50;
  string mirror_url = 51;
  string hooks_url = 52;
  string svn_url = 53;
  string homepage = 54;
  string language = 55;
  int64 forks_count = 56;
  int64 stargazers_count = 57;
  int64 watchers_count = 58;
  int64 size = 59;
  string default_branch = 60;
  int64 open_issues_count = 61;
  bool is_template = 62;
  repeated string topics = 63;
  bool has_issues = 64;
  bool has_projects = 65;
  bool has_wiki = 66;
  bool has_pages = 67;
  bool has_discussions = 68;
  bool has_pull_requests = 69;
  string pull_request_creation_policy = 70;
  bool archived = 71;
  bool disabled = 72;
  string visibility = 73;
  string pushed_at = 74;
  string created_at = 75;
  string updated_at = 76;
  Permissions permissions = 77;
  bool allow_rebase_merge = 78;
  GitHubReposReposRepository template_repository = 79;
  string temp_clone_token = 80;
  bool allow_squash_merge = 81;
  bool allow_auto_merge = 82;
  bool delete_branch_on_merge = 83;
  bool allow_merge_commit = 84;
  bool allow_update_branch = 85;
  string squash_merge_commit_title = 86;
  string squash_merge_commit_message = 87;
  string merge_commit_title = 88;
  string merge_commit_message = 89;
  bool allow_forking = 90;
  bool web_commit_signoff_required = 91;
  int64 subscribers_count = 92;
  int64 network_count = 93;
  GitHubReposReposLicenseSimple license = 94;
  GitHubReposReposSimpleUser organization = 95;
  GitHubReposReposRepository parent = 96;
  GitHubReposReposRepository source = 97;
  int64 forks = 98;
  string master_branch = 99;
  int64 open_issues = 100;
  int64 watchers = 101;
  bool anonymous_access_enabled = 102;
  GitHubReposReposCodeOfConductSimple code_of_conduct = 103;
  SecurityAndAnalysis security_and_analysis = 104;
  google.protobuf.Struct custom_properties = 105;
}

message GitHubReposReposGetARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposUpdateARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposDeleteARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposDeleteARepositoryResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposListRepositoryActivitiesRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoryActivitiesResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubReposReposActivity items = 3;
}

message GitHubReposReposCheckIfDependabotSecurityUpdatesAreEnabledForARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposCheckIfDependabotSecurityUpdatesAreEnabledForARepositoryResponse {
  bool success = 1;
  string error = 2;
  bool enabled = 3;
  bool paused = 4;
}

message GitHubReposReposEnableDependabotSecurityUpdatesRequest {
  string namespace = 1;
}

message GitHubReposReposEnableDependabotSecurityUpdatesResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposDisableDependabotSecurityUpdatesRequest {
  string namespace = 1;
}

message GitHubReposReposDisableDependabotSecurityUpdatesResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposListCODEOWNERSErrorsRequest {
  string namespace = 1;
}

message GitHubReposReposListCODEOWNERSErrorsResponse {
  message Errors {
    int64 line = 1;
    int64 column = 2;
    string source = 3;
    string kind = 4;
    string suggestion = 5;
    string message = 6;
    string path = 7;
  }
  bool success = 1;
  string error = 2;
  repeated Errors errors = 3;
}

message GitHubReposReposListRepositoryContributorsRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoryContributorsResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubReposReposContributor items = 3;
}

message GitHubReposReposCreateARepositoryDispatchEventRequest {
  string namespace = 1;
}

message GitHubReposReposCreateARepositoryDispatchEventResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposGetTheHashAlgorithmForARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposGetTheHashAlgorithmForARepositoryResponse {
  bool success = 1;
  string error = 2;
  string hash_algorithm = 3;
}

message GitHubReposReposCheckIfImmutableReleasesAreEnabledForARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposCheckIfImmutableReleasesAreEnabledForARepositoryResponse {
  bool success = 1;
  string error = 2;
  bool enabled = 3;
  bool enforced_by_owner = 4;
}

message GitHubReposReposEnableImmutableReleasesRequest {
  string namespace = 1;
}

message GitHubReposReposEnableImmutableReleasesResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposDisableImmutableReleasesRequest {
  string namespace = 1;
}

message GitHubReposReposDisableImmutableReleasesResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposListRepositoryLanguagesRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoryLanguagesResponse {
  bool success = 1;
  string error = 2;
  google.protobuf.Value body = 3;
}

message GitHubReposReposCheckIfPrivateVulnerabilityReportingIsEnabledForARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposCheckIfPrivateVulnerabilityReportingIsEnabledForARepositoryResponse {
  bool success = 1;
  string error = 2;
  bool enabled = 3;
}

message GitHubReposReposEnablePrivateVulnerabilityReportingForARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposEnablePrivateVulnerabilityReportingForARepositoryResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposDisablePrivateVulnerabilityReportingForARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposDisablePrivateVulnerabilityReportingForARepositoryResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposListRepositoryTagsRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoryTagsResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubReposReposTag items = 3;
}

message GitHubReposReposListRepositoryTeamsRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoryTeamsResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubReposReposTeam items = 3;
}

message GitHubReposReposGetAllRepositoryTopicsRequest {
  string namespace = 1;
}

message GitHubReposReposGetAllRepositoryTopicsResponse {
  bool success = 1;
  string error = 2;
  repeated string names = 3;
}

message GitHubReposReposReplaceAllRepositoryTopicsRequest {
  string namespace = 1;
}

message GitHubReposReposTransferARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposTransferARepositoryResponse {
  message Permissions {
    bool admin = 1;
    bool maintain = 2;
    bool push = 3;
    bool triage = 4;
    bool pull = 5;
  }
  message License {
    string key = 1;
    string name = 2;
    string spdx_id = 3;
    string url = 4;
    string node_id = 5;
  }
  message SecurityAndAnalysis {
    message AdvancedSecurity {
      string status = 1;
    }
    message CodeSecurity {
      string status = 1;
    }
    message DependabotSecurityUpdates {
      string status = 1;
    }
    message SecretScanning {
      string status = 1;
    }
    message SecretScanningPushProtection {
      string status = 1;
    }
    message SecretScanningNonProviderPatterns {
      string status = 1;
    }
    message SecretScanningAiDetection {
      string status = 1;
    }
    message SecretScanningDelegatedAlertDismissal {
      string status = 1;
    }
    message SecretScanningDelegatedBypass {
      string status = 1;
    }
    message SecretScanningDelegatedBypassOptions {
      message Reviewers {
        int64 reviewer_id = 1;
        string reviewer_type = 2;
        string mode = 3;
      }
      repeated Reviewers reviewers = 1;
    }
    AdvancedSecurity advanced_security = 1;
    CodeSecurity code_security = 2;
    DependabotSecurityUpdates dependabot_security_updates = 3;
    SecretScanning secret_scanning = 4;
    SecretScanningPushProtection secret_scanning_push_protection = 5;
    SecretScanningNonProviderPatterns secret_scanning_non_provider_patterns = 6;
    SecretScanningAiDetection secret_scanning_ai_detection = 7;
    SecretScanningDelegatedAlertDismissal secret_scanning_delegated_alert_dismissal = 8;
    SecretScanningDelegatedBypass secret_scanning_delegated_bypass = 9;
    SecretScanningDelegatedBypassOptions secret_scanning_delegated_bypass_options = 10;
  }
  bool success = 1;
  string error = 2;
  int64 id = 3;
  string node_id = 4;
  string name = 5;
  string full_name = 6;
  GitHubReposReposSimpleUser owner = 7;
  bool private = 8;
  string html_url = 9;
  string description = 10;
  bool fork = 11;
  string url = 12;
  string archive_url = 13;
  string assignees_url = 14;
  string blobs_url = 15;
  string branches_url = 16;
  string collaborators_url = 17;
  string comments_url = 18;
  string commits_url = 19;
  string compare_url = 20;
  string contents_url = 21;
  string contributors_url = 22;
  string deployments_url = 23;
  string downloads_url = 24;
  string events_url = 25;
  string forks_url = 26;
  string git_commits_url = 27;
  string git_refs_url = 28;
  string git_tags_url = 29;
  string git_url = 30;
  string issue_comment_url = 31;
  string issue_events_url = 32;
  string issues_url = 33;
  string keys_url = 34;
  string labels_url = 35;
  string languages_url = 36;
  string merges_url = 37;
  string milestones_url = 38;
  string notifications_url = 39;
  string pulls_url = 40;
  string releases_url = 41;
  string ssh_url = 42;
  string stargazers_url = 43;
  string statuses_url = 44;
  string subscribers_url = 45;
  string subscription_url = 46;
  string tags_url = 47;
  string teams_url = 48;
  string trees_url = 49;
  string clone_url = 50;
  string mirror_url = 51;
  string hooks_url = 52;
  string svn_url = 53;
  string homepage = 54;
  string language = 55;
  int64 forks_count = 56;
  int64 stargazers_count = 57;
  int64 watchers_count = 58;
  int64 size = 59;
  string default_branch = 60;
  int64 open_issues_count = 61;
  bool is_template = 62;
  repeated string topics = 63;
  bool has_issues = 64;
  bool has_projects = 65;
  bool has_wiki = 66;
  bool has_pages = 67;
  bool has_discussions = 68;
  bool has_pull_requests = 69;
  string pull_request_creation_policy = 70;
  bool archived = 71;
  bool disabled = 72;
  string visibility = 73;
  string pushed_at = 74;
  string created_at = 75;
  string updated_at = 76;
  Permissions permissions = 77;
  string role_name = 78;
  string temp_clone_token = 79;
  bool delete_branch_on_merge = 80;
  int64 subscribers_count = 81;
  int64 network_count = 82;
  GitHubReposReposCodeOfConduct code_of_conduct = 83;
  License license = 84;
  int64 forks = 85;
  int64 open_issues = 86;
  int64 watchers = 87;
  bool allow_forking = 88;
  bool web_commit_signoff_required = 89;
  SecurityAndAnalysis security_and_analysis = 90;
  google.protobuf.Struct custom_properties = 91;
}

message GitHubReposReposCheckIfVulnerabilityAlertsAreEnabledForARepositoryRequest {
  string namespace = 1;
}

message GitHubReposReposCheckIfVulnerabilityAlertsAreEnabledForARepositoryResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposEnableVulnerabilityAlertsRequest {
  string namespace = 1;
}

message GitHubReposReposEnableVulnerabilityAlertsResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposDisableVulnerabilityAlertsRequest {
  string namespace = 1;
}

message GitHubReposReposDisableVulnerabilityAlertsResponse {
  bool success = 1;
  string error = 2;
}

message GitHubReposReposCreateARepositoryUsingATemplateRequest {
  string namespace = 1;
}

message GitHubReposReposListPublicRepositoriesRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoriesForTheAuthenticatedUserRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoriesForTheAuthenticatedUserResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubReposReposRepository items = 3;
}

message GitHubReposReposCreateARepositoryForTheAuthenticatedUserRequest {
  string namespace = 1;
}

message GitHubReposReposListRepositoriesForAUserRequest {
  string namespace = 1;
}

message GitHubReposReposSimpleUser {
  string name = 1;
  string email = 2;
  string login = 3;
  int64 id = 4;
  string node_id = 5;
  string avatar_url = 6;
  string gravatar_id = 7;
  string url = 8;
  string html_url = 9;
  string followers_url = 10;
  string following_url = 11;
  string gists_url = 12;
  string starred_url = 13;
  string subscriptions_url = 14;
  string organizations_url = 15;
  string repos_url = 16;
  string events_url = 17;
  string received_events_url = 18;
  string type = 19;
  bool site_admin = 20;
  string starred_at = 21;
  string user_view_type = 22;
}

message GitHubReposReposCodeOfConduct {
  string key = 1;
  string name = 2;
  string url = 3;
  string body = 4;
  string html_url = 5;
}

message GitHubReposReposMinimalRepository {
  message Permissions {
    bool admin = 1;
    bool maintain = 2;
    bool push = 3;
    bool triage = 4;
    bool pull = 5;
  }
  message License {
    string key = 1;
    string name = 2;
    string spdx_id = 3;
    string url = 4;
    string node_id = 5;
  }
  message SecurityAndAnalysis {
    message AdvancedSecurity {
      string status = 1;
    }
    message CodeSecurity {
      string status = 1;
    }
    message DependabotSecurityUpdates {
      string status = 1;
    }
    message SecretScanning {
      string status = 1;
    }
    message SecretScanningPushProtection {
      string status = 1;
    }
    message SecretScanningNonProviderPatterns {
      string status = 1;
    }
    message SecretScanningAiDetection {
      string status = 1;
    }
    message SecretScanningDelegatedAlertDismissal {
      string status = 1;
    }
    message SecretScanningDelegatedBypass {
      string status = 1;
    }
    message SecretScanningDelegatedBypassOptions {
      message Reviewers {
        int64 reviewer_id = 1;
        string reviewer_type = 2;
        string mode = 3;
      }
      repeated Reviewers reviewers = 1;
    }
    AdvancedSecurity advanced_security = 1;
    CodeSecurity code_security = 2;
    DependabotSecurityUpdates dependabot_security_updates = 3;
    SecretScanning secret_scanning = 4;
    SecretScanningPushProtection secret_scanning_push_protection = 5;
    SecretScanningNonProviderPatterns secret_scanning_non_provider_patterns = 6;
    SecretScanningAiDetection secret_scanning_ai_detection = 7;
    SecretScanningDelegatedAlertDismissal secret_scanning_delegated_alert_dismissal = 8;
    SecretScanningDelegatedBypass secret_scanning_delegated_bypass = 9;
    SecretScanningDelegatedBypassOptions secret_scanning_delegated_bypass_options = 10;
  }
  int64 id = 1;
  string node_id = 2;
  string name = 3;
  string full_name = 4;
  GitHubReposReposSimpleUser owner = 5;
  bool private = 6;
  string html_url = 7;
  string description = 8;
  bool fork = 9;
  string url = 10;
  string archive_url = 11;
  string assignees_url = 12;
  string blobs_url = 13;
  string branches_url = 14;
  string collaborators_url = 15;
  string comments_url = 16;
  string commits_url = 17;
  string compare_url = 18;
  string contents_url = 19;
  string contributors_url = 20;
  string deployments_url = 21;
  string downloads_url = 22;
  string events_url = 23;
  string forks_url = 24;
  string git_commits_url = 25;
  string git_refs_url = 26;
  string git_tags_url = 27;
  string git_url = 28;
  string issue_comment_url = 29;
  string issue_events_url = 30;
  string issues_url = 31;
  string keys_url = 32;
  string labels_url = 33;
  string languages_url = 34;
  string merges_url = 35;
  string milestones_url = 36;
  string notifications_url = 37;
  string pulls_url = 38;
  string releases_url = 39;
  string ssh_url = 40;
  string stargazers_url = 41;
  string statuses_url = 42;
  string subscribers_url = 43;
  string subscription_url = 44;
  string tags_url = 45;
  string teams_url = 46;
  string trees_url = 47;
  string clone_url = 48;
  string mirror_url = 49;
  string hooks_url = 50;
  string svn_url = 51;
  string homepage = 52;
  string language = 53;
  int64 forks_count = 54;
  int64 stargazers_count = 55;
  int64 watchers_count = 56;
  int64 size = 57;
  string default_branch = 58;
  int64 open_issues_count = 59;
  bool is_template = 60;
  repeated string topics = 61;
  bool has_issues = 62;
  bool has_projects = 63;
  bool has_wiki = 64;
  bool has_pages = 65;
  bool has_discussions = 66;
  bool has_pull_requests = 67;
  string pull_request_creation_policy = 68;
  bool archived = 69;
  bool disabled = 70;
  string visibility = 71;
  string pushed_at = 72;
  string created_at = 73;
  string updated_at = 74;
  Permissions permissions = 75;
  string role_name = 76;
  string temp_clone_token = 77;
  bool delete_branch_on_merge = 78;
  int64 subscribers_count = 79;
  int64 network_count = 80;
  GitHubReposReposCodeOfConduct code_of_conduct = 81;
  License license = 82;
  int64 forks = 83;
  int64 open_issues = 84;
  int64 watchers = 85;
  bool allow_forking = 86;
  bool web_commit_signoff_required = 87;
  SecurityAndAnalysis security_and_analysis = 88;
  google.protobuf.Struct custom_properties = 89;
}

message GitHubReposReposLicenseSimple {
  string key = 1;
  string name = 2;
  string url = 3;
  string spdx_id = 4;
  string node_id = 5;
  string html_url = 6;
}

message GitHubReposReposRepository {
  message Permissions {
    bool admin = 1;
    bool pull = 2;
    bool triage = 3;
    bool push = 4;
    bool maintain = 5;
  }
  message CodeSearchIndexStatus {
    bool lexical_search_ok = 1;
    string lexical_commit_sha = 2;
  }
  int64 id = 1;
  string node_id = 2;
  string name = 3;
  string full_name = 4;
  GitHubReposReposLicenseSimple license = 5;
  int64 forks = 6;
  Permissions permissions = 7;
  GitHubReposReposSimpleUser owner = 8;
  bool private = 9;
  string html_url = 10;
  string description = 11;
  bool fork = 12;
  string url = 13;
  string archive_url = 14;
  string assignees_url = 15;
  string blobs_url = 16;
  string branches_url = 17;
  string collaborators_url = 18;
  string comments_url = 19;
  string commits_url = 20;
  string compare_url = 21;
  string contents_url = 22;
  string contributors_url = 23;
  string deployments_url = 24;
  string downloads_url = 25;
  string events_url = 26;
  string forks_url = 27;
  string git_commits_url = 28;
  string git_refs_url = 29;
  string git_tags_url = 30;
  string git_url = 31;
  string issue_comment_url = 32;
  string issue_events_url = 33;
  string issues_url = 34;
  string keys_url = 35;
  string labels_url = 36;
  string languages_url = 37;
  string merges_url = 38;
  string milestones_url = 39;
  string notifications_url = 40;
  string pulls_url = 41;
  string releases_url = 42;
  string ssh_url = 43;
  string stargazers_url = 44;
  string statuses_url = 45;
  string subscribers_url = 46;
  string subscription_url = 47;
  string tags_url = 48;
  string teams_url = 49;
  string trees_url = 50;
  string clone_url = 51;
  string mirror_url = 52;
  string hooks_url = 53;
  string svn_url = 54;
  string homepage = 55;
  string language = 56;
  int64 forks_count = 57;
  int64 stargazers_count = 58;
  int64 watchers_count = 59;
  int64 size = 60;
  string default_branch = 61;
  int64 open_issues_count = 62;
  bool is_template = 63;
  repeated string topics = 64;
  bool has_issues = 65;
  bool has_projects = 66;
  bool has_wiki = 67;
  bool has_pages = 68;
  bool has_discussions = 69;
  bool has_pull_requests = 70;
  string pull_request_creation_policy = 71;
  bool archived = 72;
  bool disabled = 73;
  string visibility = 74;
  string pushed_at = 75;
  string created_at = 76;
  string updated_at = 77;
  bool allow_rebase_merge = 78;
  string temp_clone_token = 79;
  bool allow_squash_merge = 80;
  bool allow_auto_merge = 81;
  bool delete_branch_on_merge = 82;
  bool allow_update_branch = 83;
  string squash_merge_commit_title = 84;
  string squash_merge_commit_message = 85;
  string merge_commit_title = 86;
  string merge_commit_message = 87;
  bool allow_merge_commit = 88;
  bool allow_forking = 89;
  bool web_commit_signoff_required = 90;
  int64 open_issues = 91;
  int64 watchers = 92;
  string starred_at = 93;
  bool anonymous_access_enabled = 94;
  CodeSearchIndexStatus code_search_index_status = 95;
}

message GitHubReposReposCodeOfConductSimple {
  string url = 1;
  string key = 2;
  string name = 3;
  string html_url = 4;
}

message GitHubReposReposActivity {
  int64 id = 1;
  string node_id = 2;
  string before = 3;
  string after = 4;
  string ref = 5;
  string timestamp = 6;
  string activity_type = 7;
  GitHubReposReposSimpleUser actor = 8;
}

message GitHubReposReposContributor {
  string login = 1;
  int64 id = 2;
  string node_id = 3;
  string avatar_url = 4;
  string gravatar_id = 5;
  string url = 6;
  string html_url = 7;
  string followers_url = 8;
  string following_url = 9;
  string gists_url = 10;
  string starred_url = 11;
  string subscriptions_url = 12;
  string organizations_url = 13;
  string repos_url = 14;
  string events_url = 15;
  string received_events_url = 16;
  string type = 17;
  bool site_admin = 18;
  int64 contributions = 19;
  string email = 20;
  string name = 21;
  string user_view_type = 22;
}

message GitHubReposReposTag {
  message Commit {
    string sha = 1;
    string url = 2;
  }
  string name = 1;
  Commit commit = 2;
  string zipball_url = 3;
  string tarball_url = 4;
  string node_id = 5;
}

message GitHubReposReposTeamSimple {
  int64 id = 1;
  string node_id = 2;
  string url = 3;
  string members_url = 4;
  string name = 5;
  string description = 6;
  string permission = 7;
  string privacy = 8;
  string notification_setting = 9;
  string html_url = 10;
  string repositories_url = 11;
  string slug = 12;
  string ldap_dn = 13;
  string type = 14;
  int64 organization_id = 15;
  int64 enterprise_id = 16;
}

message GitHubReposReposTeam {
  message Permissions {
    bool pull = 1;
    bool triage = 2;
    bool push = 3;
    bool maintain = 4;
    bool admin = 5;
  }
  int64 id = 1;
  string node_id = 2;
  string name = 3;
  string slug = 4;
  string description = 5;
  string privacy = 6;
  string notification_setting = 7;
  string permission = 8;
  Permissions permissions = 9;
  string url = 10;
  string html_url = 11;
  string members_url = 12;
  string repositories_url = 13;
  string type = 14;
  string access_source = 15;
  int64 organization_id = 16;
  int64 enterprise_id = 17;
  GitHubReposReposTeamSimple parent = 18;
}
