syntax = "proto3";

package protocol;

option go_package = "github.com/teranos/QNTX/plugin/grpc/protocol";

// ADR-043
// https://docs.github.com/en/rest/orgs/members?apiVersion=2026-03-10

message GitHubOrgsMembersListFailedOrganizationInvitationsRequest {
  string namespace = 1;
}

message GitHubOrgsMembersListFailedOrganizationInvitationsResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubOrgsMembersOrganizationInvitation items = 3;
}

message GitHubOrgsMembersListPendingOrganizationInvitationsRequest {
  string namespace = 1;
}

message GitHubOrgsMembersCreateAnOrganizationInvitationRequest {
  string namespace = 1;
}

message GitHubOrgsMembersCreateAnOrganizationInvitationResponse {
  bool success = 1;
  string error = 2;
  int64 id = 3;
  string login = 4;
  string email = 5;
  string role = 6;
  string created_at = 7;
  string failed_at = 8;
  string failed_reason = 9;
  GitHubOrgsMembersSimpleUser inviter = 10;
  int64 team_count = 11;
  string node_id = 12;
  string invitation_teams_url = 13;
  string invitation_source = 14;
}

message GitHubOrgsMembersCancelAnOrganizationInvitationRequest {
  string namespace = 1;
}

message GitHubOrgsMembersCancelAnOrganizationInvitationResponse {
  bool success = 1;
  string error = 2;
}

message GitHubOrgsMembersListOrganizationInvitationTeamsRequest {
  string namespace = 1;
}

message GitHubOrgsMembersListOrganizationInvitationTeamsResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubOrgsMembersTeam items = 3;
}

message GitHubOrgsMembersListOrganizationMembersRequest {
  string namespace = 1;
}

message GitHubOrgsMembersListOrganizationMembersResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubOrgsMembersSimpleUser items = 3;
}

message GitHubOrgsMembersCheckOrganizationMembershipForAUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersCheckOrganizationMembershipForAUserResponse {
  bool success = 1;
  string error = 2;
}

message GitHubOrgsMembersRemoveAnOrganizationMemberRequest {
  string namespace = 1;
}

message GitHubOrgsMembersRemoveAnOrganizationMemberResponse {
  bool success = 1;
  string error = 2;
}

message GitHubOrgsMembersGetOrganizationMembershipForAUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersGetOrganizationMembershipForAUserResponse {
  message Permissions {
    bool can_create_repository = 1;
  }
  bool success = 1;
  string error = 2;
  string url = 3;
  string state = 4;
  string role = 5;
  bool direct_membership = 6;
  repeated string enterprise_teams_providing_indirect_membership = 7;
  string organization_url = 8;
  GitHubOrgsMembersOrganizationSimple organization = 9;
  GitHubOrgsMembersSimpleUser user = 10;
  Permissions permissions = 11;
}

message GitHubOrgsMembersSetOrganizationMembershipForAUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersRemoveOrganizationMembershipForAUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersRemoveOrganizationMembershipForAUserResponse {
  bool success = 1;
  string error = 2;
}

message GitHubOrgsMembersListPublicOrganizationMembersRequest {
  string namespace = 1;
}

message GitHubOrgsMembersCheckPublicOrganizationMembershipForAUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersCheckPublicOrganizationMembershipForAUserResponse {
  bool success = 1;
  string error = 2;
}

message GitHubOrgsMembersSetPublicOrganizationMembershipForTheAuthenticatedUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersSetPublicOrganizationMembershipForTheAuthenticatedUserResponse {
  bool success = 1;
  string error = 2;
}

message GitHubOrgsMembersRemovePublicOrganizationMembershipForTheAuthenticatedUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersRemovePublicOrganizationMembershipForTheAuthenticatedUserResponse {
  bool success = 1;
  string error = 2;
}

message GitHubOrgsMembersListOrganizationMembershipsForTheAuthenticatedUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersListOrganizationMembershipsForTheAuthenticatedUserResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubOrgsMembersOrgMembership items = 3;
}

message GitHubOrgsMembersGetAnOrganizationMembershipForTheAuthenticatedUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersUpdateAnOrganizationMembershipForTheAuthenticatedUserRequest {
  string namespace = 1;
}

message GitHubOrgsMembersSimpleUser {
  string name = 1;
  string email = 2;
  string login = 3;
  int64 id = 4;
  string node_id = 5;
  string avatar_url = 6;
  string gravatar_id = 7;
  string url = 8;
  string html_url = 9;
  string followers_url = 10;
  string following_url = 11;
  string gists_url = 12;
  string starred_url = 13;
  string subscriptions_url = 14;
  string organizations_url = 15;
  string repos_url = 16;
  string events_url = 17;
  string received_events_url = 18;
  string type = 19;
  bool site_admin = 20;
  string starred_at = 21;
  string user_view_type = 22;
}

message GitHubOrgsMembersOrganizationInvitation {
  int64 id = 1;
  string login = 2;
  string email = 3;
  string role = 4;
  string created_at = 5;
  string failed_at = 6;
  string failed_reason = 7;
  GitHubOrgsMembersSimpleUser inviter = 8;
  int64 team_count = 9;
  string node_id = 10;
  string invitation_teams_url = 11;
  string invitation_source = 12;
}

message GitHubOrgsMembersTeamSimple {
  int64 id = 1;
  string node_id = 2;
  string url = 3;
  string members_url = 4;
  string name = 5;
  string description = 6;
  string permission = 7;
  string privacy = 8;
  string notification_setting = 9;
  string html_url = 10;
  string repositories_url = 11;
  string slug = 12;
  string ldap_dn = 13;
  string type = 14;
  int64 organization_id = 15;
  int64 enterprise_id = 16;
}

message GitHubOrgsMembersTeam {
  message Permissions {
    bool pull = 1;
    bool triage = 2;
    bool push = 3;
    bool maintain = 4;
    bool admin = 5;
  }
  int64 id = 1;
  string node_id = 2;
  string name = 3;
  string slug = 4;
  string description = 5;
  string privacy = 6;
  string notification_setting = 7;
  string permission = 8;
  Permissions permissions = 9;
  string url = 10;
  string html_url = 11;
  string members_url = 12;
  string repositories_url = 13;
  string type = 14;
  string access_source = 15;
  int64 organization_id = 16;
  int64 enterprise_id = 17;
  GitHubOrgsMembersTeamSimple parent = 18;
}

message GitHubOrgsMembersOrganizationSimple {
  string login = 1;
  int64 id = 2;
  string node_id = 3;
  string url = 4;
  string repos_url = 5;
  string events_url = 6;
  string hooks_url = 7;
  string issues_url = 8;
  string members_url = 9;
  string public_members_url = 10;
  string avatar_url = 11;
  string description = 12;
}

message GitHubOrgsMembersOrgMembership {
  message Permissions {
    bool can_create_repository = 1;
  }
  string url = 1;
  string state = 2;
  string role = 3;
  bool direct_membership = 4;
  repeated string enterprise_teams_providing_indirect_membership = 5;
  string organization_url = 6;
  GitHubOrgsMembersOrganizationSimple organization = 7;
  GitHubOrgsMembersSimpleUser user = 8;
  Permissions permissions = 9;
}
