// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: plugin/grpc/protocol/github.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitHubRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubRateLimitRequest) Reset() {
	*x = GitHubRateLimitRequest{}
	mi := &file_plugin_grpc_protocol_github_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubRateLimitRequest) ProtoMessage() {}

func (x *GitHubRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_github_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubRateLimitRequest.ProtoReflect.Descriptor instead.
func (*GitHubRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_github_proto_rawDescGZIP(), []int{0}
}

func (x *GitHubRateLimitRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GitHubRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Remaining     int64                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Reset_        int64                  `protobuf:"varint,3,opt,name=reset,proto3" json:"reset,omitempty"`
	Used          int64                  `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubRate) Reset() {
	*x = GitHubRate{}
	mi := &file_plugin_grpc_protocol_github_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubRate) ProtoMessage() {}

func (x *GitHubRate) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_github_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubRate.ProtoReflect.Descriptor instead.
func (*GitHubRate) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_github_proto_rawDescGZIP(), []int{1}
}

func (x *GitHubRate) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GitHubRate) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *GitHubRate) GetReset_() int64 {
	if x != nil {
		return x.Reset_
	}
	return 0
}

func (x *GitHubRate) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

type GitHubRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Resources     map[string]*GitHubRate `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubRateLimitResponse) Reset() {
	*x = GitHubRateLimitResponse{}
	mi := &file_plugin_grpc_protocol_github_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubRateLimitResponse) ProtoMessage() {}

func (x *GitHubRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_github_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubRateLimitResponse.ProtoReflect.Descriptor instead.
func (*GitHubRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_github_proto_rawDescGZIP(), []int{2}
}

func (x *GitHubRateLimitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GitHubRateLimitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GitHubRateLimitResponse) GetResources() map[string]*GitHubRate {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_plugin_grpc_protocol_github_proto protoreflect.FileDescriptor

const file_plugin_grpc_protocol_github_proto_rawDesc = "" +
	"\n" +
	"!plugin/grpc/protocol/github.proto\x12\bprotocol\"6\n" +
	"\x16GitHubRateLimitRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"j\n" +
	"\n" +
	"GitHubRate\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12\x14\n" +
	"\x05reset\x18\x03 \x01(\x03R\x05reset\x12\x12\n" +
	"\x04used\x18\x04 \x01(\x03R\x04used\"\xed\x01\n" +
	"\x17GitHubRateLimitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12N\n" +
	"\tresources\x18\x03 \x03(\v20.protocol.GitHubRateLimitResponse.ResourcesEntryR\tresources\x1aR\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protocol.GitHubRateR\x05value:\x028\x012a\n" +
	"\rGitHubService\x12P\n" +
	"\tRateLimit\x12 .protocol.GitHubRateLimitRequest\x1a!.protocol.GitHubRateLimitResponseB.Z,github.com/teranos/QNTX/plugin/grpc/protocolb\x06proto3"

var (
	file_plugin_grpc_protocol_github_proto_rawDescOnce sync.Once
	file_plugin_grpc_protocol_github_proto_rawDescData []byte
)

func file_plugin_grpc_protocol_github_proto_rawDescGZIP() []byte {
	file_plugin_grpc_protocol_github_proto_rawDescOnce.Do(func() {
		file_plugin_grpc_protocol_github_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_github_proto_rawDesc), len(file_plugin_grpc_protocol_github_proto_rawDesc)))
	})
	return file_plugin_grpc_protocol_github_proto_rawDescData
}

var file_plugin_grpc_protocol_github_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugin_grpc_protocol_github_proto_goTypes = []any{
	(*GitHubRateLimitRequest)(nil),  // 0: protocol.GitHubRateLimitRequest
	(*GitHubRate)(nil),              // 1: protocol.GitHubRate
	(*GitHubRateLimitResponse)(nil), // 2: protocol.GitHubRateLimitResponse
	nil,                             // 3: protocol.GitHubRateLimitResponse.ResourcesEntry
}
var file_plugin_grpc_protocol_github_proto_depIdxs = []int32{
	3, // 0: protocol.GitHubRateLimitResponse.resources:type_name -> protocol.GitHubRateLimitResponse.ResourcesEntry
	1, // 1: protocol.GitHubRateLimitResponse.ResourcesEntry.value:type_name -> protocol.GitHubRate
	0, // 2: protocol.GitHubService.RateLimit:input_type -> protocol.GitHubRateLimitRequest
	2, // 3: protocol.GitHubService.RateLimit:output_type -> protocol.GitHubRateLimitResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_grpc_protocol_github_proto_init() }
func file_plugin_grpc_protocol_github_proto_init() {
	if File_plugin_grpc_protocol_github_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_github_proto_rawDesc), len(file_plugin_grpc_protocol_github_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_grpc_protocol_github_proto_goTypes,
		DependencyIndexes: file_plugin_grpc_protocol_github_proto_depIdxs,
		MessageInfos:      file_plugin_grpc_protocol_github_proto_msgTypes,
	}.Build()
	File_plugin_grpc_protocol_github_proto = out.File
	file_plugin_grpc_protocol_github_proto_goTypes = nil
	file_plugin_grpc_protocol_github_proto_depIdxs = nil
}
