syntax = "proto3";

package protocol;

option go_package = "github.com/teranos/QNTX/plugin/grpc/protocol";

// ADR-043
// https://docs.github.com/en/rest/commits/comments?apiVersion=2026-03-10

// GET /repos/{owner}/{repo}/comments
message GitHubListCommitCommentsForARepositoryRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  int64 per_page = 4;
  int64 page = 5;
}

message GitHubListCommitCommentsForARepositoryResponse {
  bool success = 1;
  string error = 2;
  repeated GitHubCommitsCommentsCommitComment items = 3;
}

// GET /repos/{owner}/{repo}/comments/{comment_id}
message GitHubGetACommitCommentRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  int64 comment_id = 4;
}

message GitHubGetACommitCommentResponse {
  bool success = 1;
  string error = 2;
  string html_url = 3;
  string url = 4;
  int64 id = 5;
  string node_id = 6;
  string body = 7;
  string path = 8;
  int64 position = 9;
  int64 line = 10;
  string commit_id = 11;
  GitHubCommitsCommentsSimpleUser user = 12;
  string created_at = 13;
  string updated_at = 14;
  string author_association = 15;
  GitHubCommitsCommentsReactionRollup reactions = 16;
}

// PATCH /repos/{owner}/{repo}/comments/{comment_id}
// Response: same response schema as Get a commit comment.
message GitHubUpdateACommitCommentRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  int64 comment_id = 4;
  string body = 5;
}

// DELETE /repos/{owner}/{repo}/comments/{comment_id}
message GitHubDeleteACommitCommentRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  int64 comment_id = 4;
}

message GitHubDeleteACommitCommentResponse {
  bool success = 1;
  string error = 2;
}

// GET /repos/{owner}/{repo}/commits/{commit_sha}/comments
// Response: same response schema as List commit comments for a repository.
message GitHubListCommitCommentsRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  string commit_sha = 4;
  int64 per_page = 5;
  int64 page = 6;
}

// POST /repos/{owner}/{repo}/commits/{commit_sha}/comments
// Response: same response schema as Get a commit comment.
message GitHubCreateACommitCommentRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  string commit_sha = 4;
  string body = 5;
  string path = 6;
  int64 position = 7;
  int64 line = 8;
}

// Commit Comment
message GitHubCommitsCommentsCommitComment {
  string html_url = 1;
  string url = 2;
  int64 id = 3;
  string node_id = 4;
  string body = 5;
  string path = 6;
  int64 position = 7;
  int64 line = 8;
  string commit_id = 9;
  GitHubCommitsCommentsSimpleUser user = 10;
  string created_at = 11;
  string updated_at = 12;
  string author_association = 13;
  GitHubCommitsCommentsReactionRollup reactions = 14;
}

// Simple User
message GitHubCommitsCommentsSimpleUser {
  string name = 1;
  string email = 2;
  string login = 3;
  int64 id = 4;
  string node_id = 5;
  string avatar_url = 6;
  string gravatar_id = 7;
  string url = 8;
  string html_url = 9;
  string followers_url = 10;
  string following_url = 11;
  string gists_url = 12;
  string starred_url = 13;
  string subscriptions_url = 14;
  string organizations_url = 15;
  string repos_url = 16;
  string events_url = 17;
  string received_events_url = 18;
  string type = 19;
  bool site_admin = 20;
  string starred_at = 21;
  string user_view_type = 22;
}

// Reaction Rollup
message GitHubCommitsCommentsReactionRollup {
  string url = 1;
  int64 total_count = 2;
  int64 plus_1 = 3 [json_name = "+1"];
  int64 minus_1 = 4 [json_name = "-1"];
  int64 laugh = 5;
  int64 confused = 6;
  int64 heart = 7;
  int64 hooray = 8;
  int64 eyes = 9;
  int64 rocket = 10;
}
