syntax = "proto3";

package protocol;

import "google/protobuf/struct.proto";

option go_package = "github.com/teranos/QNTX/plugin/grpc/protocol";

// ADR-043
// https://docs.github.com/en/rest/actions/workflows?apiVersion=2026-03-10

message GitHubActionsWorkflowsListRepositoryWorkflowsRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  int64 per_page = 4;
  int64 page = 5;
}

message GitHubActionsWorkflowsListRepositoryWorkflowsResponse {
  bool success = 1;
  string error = 2;
  int64 total_count = 3;
  repeated GitHubActionsWorkflowsWorkflow workflows = 4;
}

message GitHubActionsWorkflowsGetAWorkflowRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  string workflow_id = 4;
}

message GitHubActionsWorkflowsGetAWorkflowResponse {
  bool success = 1;
  string error = 2;
  int64 id = 3;
  string node_id = 4;
  string name = 5;
  string path = 6;
  string state = 7;
  string created_at = 8;
  string updated_at = 9;
  string url = 10;
  string html_url = 11;
  string badge_url = 12;
  string deleted_at = 13;
}

message GitHubActionsWorkflowsDisableAWorkflowRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  string workflow_id = 4;
}

message GitHubActionsWorkflowsDisableAWorkflowResponse {
  bool success = 1;
  string error = 2;
}

message GitHubActionsWorkflowsCreateAWorkflowDispatchEventRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  string workflow_id = 4;
  string ref = 5;
  google.protobuf.Struct inputs = 6;
}

message GitHubActionsWorkflowsCreateAWorkflowDispatchEventResponse {
  bool success = 1;
  string error = 2;
  int64 workflow_run_id = 3;
  string run_url = 4;
  string html_url = 5;
}

message GitHubActionsWorkflowsEnableAWorkflowRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  string workflow_id = 4;
}

message GitHubActionsWorkflowsEnableAWorkflowResponse {
  bool success = 1;
  string error = 2;
}

message GitHubActionsWorkflowsGetWorkflowUsageRequest {
  string namespace = 1;
  string owner = 2;
  string repo = 3;
  string workflow_id = 4;
}

message GitHubActionsWorkflowsGetWorkflowUsageResponse {
  message Billable {
    message Ubuntu {
      int64 total_ms = 1;
    }
    message Macos {
      int64 total_ms = 1;
    }
    message Windows {
      int64 total_ms = 1;
    }
    Ubuntu UBUNTU = 1;
    Macos MACOS = 2;
    Windows WINDOWS = 3;
  }
  bool success = 1;
  string error = 2;
  Billable billable = 3;
}

message GitHubActionsWorkflowsWorkflow {
  int64 id = 1;
  string node_id = 2;
  string name = 3;
  string path = 4;
  string state = 5;
  string created_at = 6;
  string updated_at = 7;
  string url = 8;
  string html_url = 9;
  string badge_url = 10;
  string deleted_at = 11;
}
