// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: plugin/grpc/protocol/ground.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteToGroundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Subjects      []string               `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Predicates    []string               `protobuf:"bytes,3,rep,name=predicates,proto3" json:"predicates,omitempty"`
	Contexts      []string               `protobuf:"bytes,4,rep,name=contexts,proto3" json:"contexts,omitempty"`
	Actors        []string               `protobuf:"bytes,5,rep,name=actors,proto3" json:"actors,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteToGroundRequest) Reset() {
	*x = WriteToGroundRequest{}
	mi := &file_plugin_grpc_protocol_ground_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteToGroundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToGroundRequest) ProtoMessage() {}

func (x *WriteToGroundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_ground_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToGroundRequest.ProtoReflect.Descriptor instead.
func (*WriteToGroundRequest) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_ground_proto_rawDescGZIP(), []int{0}
}

func (x *WriteToGroundRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *WriteToGroundRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *WriteToGroundRequest) GetPredicates() []string {
	if x != nil {
		return x.Predicates
	}
	return nil
}

func (x *WriteToGroundRequest) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *WriteToGroundRequest) GetActors() []string {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *WriteToGroundRequest) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *WriteToGroundRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type WriteToGroundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteToGroundResponse) Reset() {
	*x = WriteToGroundResponse{}
	mi := &file_plugin_grpc_protocol_ground_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteToGroundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToGroundResponse) ProtoMessage() {}

func (x *WriteToGroundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_ground_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToGroundResponse.ProtoReflect.Descriptor instead.
func (*WriteToGroundResponse) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_ground_proto_rawDescGZIP(), []int{1}
}

func (x *WriteToGroundResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteToGroundResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_grpc_protocol_ground_proto protoreflect.FileDescriptor

const file_plugin_grpc_protocol_ground_proto_rawDesc = "" +
	"\n" +
	"!plugin/grpc/protocol/ground.proto\x12\bprotocol\x1a\x1cgoogle/protobuf/struct.proto\"\xf6\x01\n" +
	"\x14WriteToGroundRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x1a\n" +
	"\bsubjects\x18\x02 \x03(\tR\bsubjects\x12\x1e\n" +
	"\n" +
	"predicates\x18\x03 \x03(\tR\n" +
	"predicates\x12\x1a\n" +
	"\bcontexts\x18\x04 \x03(\tR\bcontexts\x12\x16\n" +
	"\x06actors\x18\x05 \x03(\tR\x06actors\x127\n" +
	"\n" +
	"attributes\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"G\n" +
	"\x15WriteToGroundResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2a\n" +
	"\rGroundService\x12P\n" +
	"\rWriteToGround\x12\x1e.protocol.WriteToGroundRequest\x1a\x1f.protocol.WriteToGroundResponseB.Z,github.com/teranos/QNTX/plugin/grpc/protocolb\x06proto3"

var (
	file_plugin_grpc_protocol_ground_proto_rawDescOnce sync.Once
	file_plugin_grpc_protocol_ground_proto_rawDescData []byte
)

func file_plugin_grpc_protocol_ground_proto_rawDescGZIP() []byte {
	file_plugin_grpc_protocol_ground_proto_rawDescOnce.Do(func() {
		file_plugin_grpc_protocol_ground_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_ground_proto_rawDesc), len(file_plugin_grpc_protocol_ground_proto_rawDesc)))
	})
	return file_plugin_grpc_protocol_ground_proto_rawDescData
}

var file_plugin_grpc_protocol_ground_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_grpc_protocol_ground_proto_goTypes = []any{
	(*WriteToGroundRequest)(nil),  // 0: protocol.WriteToGroundRequest
	(*WriteToGroundResponse)(nil), // 1: protocol.WriteToGroundResponse
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
}
var file_plugin_grpc_protocol_ground_proto_depIdxs = []int32{
	2, // 0: protocol.WriteToGroundRequest.attributes:type_name -> google.protobuf.Struct
	0, // 1: protocol.GroundService.WriteToGround:input_type -> protocol.WriteToGroundRequest
	1, // 2: protocol.GroundService.WriteToGround:output_type -> protocol.WriteToGroundResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_grpc_protocol_ground_proto_init() }
func file_plugin_grpc_protocol_ground_proto_init() {
	if File_plugin_grpc_protocol_ground_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_ground_proto_rawDesc), len(file_plugin_grpc_protocol_ground_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_grpc_protocol_ground_proto_goTypes,
		DependencyIndexes: file_plugin_grpc_protocol_ground_proto_depIdxs,
		MessageInfos:      file_plugin_grpc_protocol_ground_proto_msgTypes,
	}.Build()
	File_plugin_grpc_protocol_ground_proto = out.File
	file_plugin_grpc_protocol_ground_proto_goTypes = nil
	file_plugin_grpc_protocol_ground_proto_depIdxs = nil
}
