// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: plugin/grpc/protocol/ground.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroundService_WriteToGround_FullMethodName = "/protocol.GroundService/WriteToGround"
)

// GroundServiceClient is the client API for GroundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GroundService provides write access to Ground's deferred news database.
// Plugins call this to surface attestations in Claude Code sessions via Ground.
type GroundServiceClient interface {
	// WriteToGround inserts an attestation into Ground's SQLite database.
	// Ground delivers these as deferred news on session Stop.
	WriteToGround(ctx context.Context, in *WriteToGroundRequest, opts ...grpc.CallOption) (*WriteToGroundResponse, error)
}

type groundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroundServiceClient(cc grpc.ClientConnInterface) GroundServiceClient {
	return &groundServiceClient{cc}
}

func (c *groundServiceClient) WriteToGround(ctx context.Context, in *WriteToGroundRequest, opts ...grpc.CallOption) (*WriteToGroundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteToGroundResponse)
	err := c.cc.Invoke(ctx, GroundService_WriteToGround_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroundServiceServer is the server API for GroundService service.
// All implementations must embed UnimplementedGroundServiceServer
// for forward compatibility.
//
// GroundService provides write access to Ground's deferred news database.
// Plugins call this to surface attestations in Claude Code sessions via Ground.
type GroundServiceServer interface {
	// WriteToGround inserts an attestation into Ground's SQLite database.
	// Ground delivers these as deferred news on session Stop.
	WriteToGround(context.Context, *WriteToGroundRequest) (*WriteToGroundResponse, error)
	mustEmbedUnimplementedGroundServiceServer()
}

// UnimplementedGroundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroundServiceServer struct{}

func (UnimplementedGroundServiceServer) WriteToGround(context.Context, *WriteToGroundRequest) (*WriteToGroundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteToGround not implemented")
}
func (UnimplementedGroundServiceServer) mustEmbedUnimplementedGroundServiceServer() {}
func (UnimplementedGroundServiceServer) testEmbeddedByValue()                       {}

// UnsafeGroundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroundServiceServer will
// result in compilation errors.
type UnsafeGroundServiceServer interface {
	mustEmbedUnimplementedGroundServiceServer()
}

func RegisterGroundServiceServer(s grpc.ServiceRegistrar, srv GroundServiceServer) {
	// If the following call panics, it indicates UnimplementedGroundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroundService_ServiceDesc, srv)
}

func _GroundService_WriteToGround_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteToGroundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundServiceServer).WriteToGround(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroundService_WriteToGround_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundServiceServer).WriteToGround(ctx, req.(*WriteToGroundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroundService_ServiceDesc is the grpc.ServiceDesc for GroundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.GroundService",
	HandlerType: (*GroundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteToGround",
			Handler:    _GroundService_WriteToGround_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/grpc/protocol/ground.proto",
}
