// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: plugin/grpc/protocol/sigil.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Signum holds the sigils of one subject: watchers is a signum, and list,
// create, read, update and delete are its sigils. To A2A a signum is a skill.
type Signum struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sigils []*Sigil               `protobuf:"bytes,2,rep,name=sigils,proto3" json:"sigils,omitempty"`
	// The shapes this signum is held to, each by its name: "Staands will be
	// Umami, one reference and not a blend." The parity sigil reads these.
	Follows       []*Follows `protobuf:"bytes,3,rep,name=follows,proto3" json:"follows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signum) Reset() {
	*x = Signum{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signum) ProtoMessage() {}

func (x *Signum) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signum.ProtoReflect.Descriptor instead.
func (*Signum) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{0}
}

func (x *Signum) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Signum) GetSigils() []*Sigil {
	if x != nil {
		return x.Sigils
	}
	return nil
}

func (x *Signum) GetFollows() []*Follows {
	if x != nil {
		return x.Follows
	}
	return nil
}

// Transcript is one agent session Ground recorded, derived from its hook
// events: transcripts read answers these. Mirrors server.transcript.
type Transcript struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Session  string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Subjects []string               `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Started  string                 `protobuf:"bytes,3,opt,name=started,proto3" json:"started,omitempty"`
	Ended    string                 `protobuf:"bytes,4,opt,name=ended,proto3" json:"ended,omitempty"`
	Turns    []*Turn                `protobuf:"bytes,5,rep,name=turns,proto3" json:"turns,omitempty"`
	// Events the store folded into sigmas (ADR-020), counted and not read.
	Folded int64 `protobuf:"varint,6,opt,name=folded,proto3" json:"folded,omitempty"`
	// The model the session started on, as its SessionStart says.
	Model string `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	// The effort its last Stop ran at, as that Stop's effort.level says.
	Effort        string `protobuf:"bytes,8,opt,name=effort,proto3" json:"effort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcript) Reset() {
	*x = Transcript{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcript) ProtoMessage() {}

func (x *Transcript) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcript.ProtoReflect.Descriptor instead.
func (*Transcript) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{1}
}

func (x *Transcript) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Transcript) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Transcript) GetStarted() string {
	if x != nil {
		return x.Started
	}
	return ""
}

func (x *Transcript) GetEnded() string {
	if x != nil {
		return x.Ended
	}
	return ""
}

func (x *Transcript) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

func (x *Transcript) GetFolded() int64 {
	if x != nil {
		return x.Folded
	}
	return 0
}

func (x *Transcript) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Transcript) GetEffort() string {
	if x != nil {
		return x.Effort
	}
	return ""
}

// Turn is one thing said or done in a session, naming the attestation it was
// read from. Mirrors server.transcriptTurn.
type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            string                 `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Speaker       string                 `protobuf:"bytes,2,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Of            string                 `protobuf:"bytes,4,opt,name=of,proto3" json:"of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{2}
}

func (x *Turn) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *Turn) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *Turn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Turn) GetOf() string {
	if x != nil {
		return x.Of
	}
	return ""
}

// Follows says which column of a reference each of a signum's fields is. The
// reference is named, not described: its own schema says what its columns are.
type Follows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Columns       []*Corresponds         `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follows) Reset() {
	*x = Follows{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follows) ProtoMessage() {}

func (x *Follows) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follows.ProtoReflect.Descriptor instead.
func (*Follows) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{3}
}

func (x *Follows) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Follows) GetColumns() []*Corresponds {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Corresponds is one field and the column it is in the reference. The field is
// named in full, message and field, so a field no sigil answers with — what a
// signum keeps rather than what it gives — is named the same way.
type Corresponds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol.Arrival.path
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// WebsiteEvent.urlPath
	Column        string `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Corresponds) Reset() {
	*x = Corresponds{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Corresponds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Corresponds) ProtoMessage() {}

func (x *Corresponds) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Corresponds.ProtoReflect.Descriptor instead.
func (*Corresponds) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{4}
}

func (x *Corresponds) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Corresponds) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

// A Sigil is one thing the node does. The function that does it is not here:
// a function is not a shape.
type Sigil struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// What it is for, in words, for somebody who has never seen the code.
	Does string `protobuf:"bytes,2,opt,name=does,proto3" json:"does,omitempty"`
	// What goes in.
	Takes []*Param `protobuf:"bytes,3,rep,name=takes,proto3" json:"takes,omitempty"`
	// What comes out, by field.
	Gives []*Field `protobuf:"bytes,4,rep,name=gives,proto3" json:"gives,omitempty"`
	// Where it answers on the HTTP API.
	Http          *Endpoint `protobuf:"bytes,5,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sigil) Reset() {
	*x = Sigil{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sigil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sigil) ProtoMessage() {}

func (x *Sigil) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sigil.ProtoReflect.Descriptor instead.
func (*Sigil) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{5}
}

func (x *Sigil) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sigil) GetDoes() string {
	if x != nil {
		return x.Does
	}
	return ""
}

func (x *Sigil) GetTakes() []*Param {
	if x != nil {
		return x.Takes
	}
	return nil
}

func (x *Sigil) GetGives() []*Field {
	if x != nil {
		return x.Gives
	}
	return nil
}

func (x *Sigil) GetHttp() *Endpoint {
	if x != nil {
		return x.Http
	}
	return nil
}

// A Param is one thing a sigil takes. It says nothing about how it travels:
// that is each surface's to decide.
type Param struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Says     string                 `protobuf:"bytes,2,opt,name=says,proto3" json:"says,omitempty"`
	Required bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	// Every value it takes, when it takes only some.
	OneOf []string `protobuf:"bytes,4,rep,name=one_of,json=oneOf,proto3" json:"one_of,omitempty"`
	// What its value is: empty is text, "count" is a whole number, zero or more.
	Kind          string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{6}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetSays() string {
	if x != nil {
		return x.Says
	}
	return ""
}

func (x *Param) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Param) GetOneOf() []string {
	if x != nil {
		return x.OneOf
	}
	return nil
}

func (x *Param) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// A Field is one thing a sigil's answer carries, at the top of the answer.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Says  string                 `protobuf:"bytes,2,opt,name=says,proto3" json:"says,omitempty"`
	// The message it carries, named in full, when it carries one: protocol.Visit.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{7}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetSays() string {
	if x != nil {
		return x.Says
	}
	return ""
}

func (x *Field) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// An Endpoint is a sigil's form in the HTTP API: the method and the whole path.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{8}
}

func (x *Endpoint) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Endpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// A Refusal is a sigil saying no, in its own terms. It names the param the
// caller has to change. Each surface gives it its form: the HTTP API a status,
// MCP a tool error.
type Refusal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kind of no: "missing", "not one of", "invalid", "not found",
	// "not allowed", "failed".
	Why           string `protobuf:"bytes,1,opt,name=why,proto3" json:"why,omitempty"`
	Param         string `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	Says          string `protobuf:"bytes,3,opt,name=says,proto3" json:"says,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refusal) Reset() {
	*x = Refusal{}
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refusal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refusal) ProtoMessage() {}

func (x *Refusal) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_grpc_protocol_sigil_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refusal.ProtoReflect.Descriptor instead.
func (*Refusal) Descriptor() ([]byte, []int) {
	return file_plugin_grpc_protocol_sigil_proto_rawDescGZIP(), []int{9}
}

func (x *Refusal) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

func (x *Refusal) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *Refusal) GetSays() string {
	if x != nil {
		return x.Says
	}
	return ""
}

var File_plugin_grpc_protocol_sigil_proto protoreflect.FileDescriptor

const file_plugin_grpc_protocol_sigil_proto_rawDesc = "" +
	"\n" +
	" plugin/grpc/protocol/sigil.proto\x12\bprotocol\"r\n" +
	"\x06Signum\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x06sigils\x18\x02 \x03(\v2\x0f.protocol.SigilR\x06sigils\x12+\n" +
	"\afollows\x18\x03 \x03(\v2\x11.protocol.FollowsR\afollows\"\xde\x01\n" +
	"\n" +
	"Transcript\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x1a\n" +
	"\bsubjects\x18\x02 \x03(\tR\bsubjects\x12\x18\n" +
	"\astarted\x18\x03 \x01(\tR\astarted\x12\x14\n" +
	"\x05ended\x18\x04 \x01(\tR\x05ended\x12$\n" +
	"\x05turns\x18\x05 \x03(\v2\x0e.protocol.TurnR\x05turns\x12\x16\n" +
	"\x06folded\x18\x06 \x01(\x03R\x06folded\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x16\n" +
	"\x06effort\x18\b \x01(\tR\x06effort\"T\n" +
	"\x04Turn\x12\x0e\n" +
	"\x02at\x18\x01 \x01(\tR\x02at\x12\x18\n" +
	"\aspeaker\x18\x02 \x01(\tR\aspeaker\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x0e\n" +
	"\x02of\x18\x04 \x01(\tR\x02of\"X\n" +
	"\aFollows\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12/\n" +
	"\acolumns\x18\x02 \x03(\v2\x15.protocol.CorrespondsR\acolumns\";\n" +
	"\vCorresponds\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\"\xa5\x01\n" +
	"\x05Sigil\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04does\x18\x02 \x01(\tR\x04does\x12%\n" +
	"\x05takes\x18\x03 \x03(\v2\x0f.protocol.ParamR\x05takes\x12%\n" +
	"\x05gives\x18\x04 \x03(\v2\x0f.protocol.FieldR\x05gives\x12&\n" +
	"\x04http\x18\x05 \x01(\v2\x12.protocol.EndpointR\x04http\"v\n" +
	"\x05Param\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04says\x18\x02 \x01(\tR\x04says\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x15\n" +
	"\x06one_of\x18\x04 \x03(\tR\x05oneOf\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\"I\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04says\x18\x02 \x01(\tR\x04says\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"6\n" +
	"\bEndpoint\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"E\n" +
	"\aRefusal\x12\x10\n" +
	"\x03why\x18\x01 \x01(\tR\x03why\x12\x14\n" +
	"\x05param\x18\x02 \x01(\tR\x05param\x12\x12\n" +
	"\x04says\x18\x03 \x01(\tR\x04saysB.Z,github.com/teranos/QNTX/plugin/grpc/protocolb\x06proto3"

var (
	file_plugin_grpc_protocol_sigil_proto_rawDescOnce sync.Once
	file_plugin_grpc_protocol_sigil_proto_rawDescData []byte
)

func file_plugin_grpc_protocol_sigil_proto_rawDescGZIP() []byte {
	file_plugin_grpc_protocol_sigil_proto_rawDescOnce.Do(func() {
		file_plugin_grpc_protocol_sigil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_sigil_proto_rawDesc), len(file_plugin_grpc_protocol_sigil_proto_rawDesc)))
	})
	return file_plugin_grpc_protocol_sigil_proto_rawDescData
}

var file_plugin_grpc_protocol_sigil_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_plugin_grpc_protocol_sigil_proto_goTypes = []any{
	(*Signum)(nil),      // 0: protocol.Signum
	(*Transcript)(nil),  // 1: protocol.Transcript
	(*Turn)(nil),        // 2: protocol.Turn
	(*Follows)(nil),     // 3: protocol.Follows
	(*Corresponds)(nil), // 4: protocol.Corresponds
	(*Sigil)(nil),       // 5: protocol.Sigil
	(*Param)(nil),       // 6: protocol.Param
	(*Field)(nil),       // 7: protocol.Field
	(*Endpoint)(nil),    // 8: protocol.Endpoint
	(*Refusal)(nil),     // 9: protocol.Refusal
}
var file_plugin_grpc_protocol_sigil_proto_depIdxs = []int32{
	5, // 0: protocol.Signum.sigils:type_name -> protocol.Sigil
	3, // 1: protocol.Signum.follows:type_name -> protocol.Follows
	2, // 2: protocol.Transcript.turns:type_name -> protocol.Turn
	4, // 3: protocol.Follows.columns:type_name -> protocol.Corresponds
	6, // 4: protocol.Sigil.takes:type_name -> protocol.Param
	7, // 5: protocol.Sigil.gives:type_name -> protocol.Field
	8, // 6: protocol.Sigil.http:type_name -> protocol.Endpoint
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_plugin_grpc_protocol_sigil_proto_init() }
func file_plugin_grpc_protocol_sigil_proto_init() {
	if File_plugin_grpc_protocol_sigil_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_grpc_protocol_sigil_proto_rawDesc), len(file_plugin_grpc_protocol_sigil_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_grpc_protocol_sigil_proto_goTypes,
		DependencyIndexes: file_plugin_grpc_protocol_sigil_proto_depIdxs,
		MessageInfos:      file_plugin_grpc_protocol_sigil_proto_msgTypes,
	}.Build()
	File_plugin_grpc_protocol_sigil_proto = out.File
	file_plugin_grpc_protocol_sigil_proto_goTypes = nil
	file_plugin_grpc_protocol_sigil_proto_depIdxs = nil
}
