(lang dune 3.0)
(using menhir 2.1)
(name kern)

(generate_opam_files true)

(package
 (name kern)
 (synopsis "OCaml Ax query parser plugin for QNTX")
 (depends
  (ocaml (>= 5.1.0))
  qntx-plugin
  sedlex
  menhir
  yojson))
