(lang dune 3.0)
(name qntx-loom)

; Generate the .opam file from this dune-project
(generate_opam_files true)

(package
 (name qntx-loom)
 (synopsis "Commit-scoped transcript stitcher for QNTX")
 (depends
  (ocaml (>= 5.1.0))
  qntx-plugin
  yojson
  uri))
