name: iOS TestFlight

on:
  push:
    branches: [mobile-builds]

jobs:
  testflight:
    name: Build and upload
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - run: cargo install tauri-cli --version "^2"

      - run: cd web/src-tauri && cargo tauri ios init
