name: iOS TestFlight

on:
  push:
    branches: [mobile-builds]

jobs:
  testflight:
    name: Build and upload
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'v0.13.1'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.3'

      - run: make web
        env:
          BACKEND_URL: https://api.q.sbvh.nl

      - run: cargo install tauri-cli --version "=2.11.4"

      - run: cd web/src-tauri && cargo tauri ios init

      - run: cd web/src-tauri && cargo tauri ios build
