{
  "jobs": {
    "build": {
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "name": "Checkout repository",
          "uses": "actions/checkout@v5",
          "with": {
            "submodules": "recursive"
          }
        },
        {
          "name": "Install Nix",
          "uses": "cachix/install-nix-action@v30",
          "with": {
            "extra_nix_config": "experimental-features = nix-command flakes\n"
          }
        },
        {
          "name": "Setup Cachix",
          "uses": "cachix/cachix-action@v14",
          "with": {
            "authToken": "${{ secrets.CACHIX_AUTH_TOKEN }}",
            "name": "qntx"
          }
        },
        {
          "name": "Build scry plugin",
          "run": "nix build ./qntx-plugins/scry --show-trace"
        },
        {
          "name": "Verify binary",
          "run": "./result/bin/qntx-scry-plugin --version"
        },
        {
          "name": "Push to Cachix",
          "run": "nix build ./qntx-plugins/scry --print-out-paths --no-link | cachix push qntx"
        }
      ],
      "strategy": {
        "matrix": {
          "os": [
            "ubuntu-latest",
            "macos-latest"
          ]
        }
      }
    }
  },
  "name": "scry",
  "on": {
    "workflow_dispatch": null
  }
}
